### ISSUE TITLE
Better NPC Sheet 5e support

### ISSUE THREAD

**Issue by geoidesic** [RedReign/FoundryVTT-BetterRolls5e#102]
Hi there. Great module!

The README says `natively supports Better NPC Sheet`, but doesn't provide a link to that module, so I'm not 100% sure which module it is referring to. I assume it is this: https://github.com/syl3r86/BetterNPCSheet5e

... however, I've tested the two modules together and `BetterNPCSheet5e` doesn't seem to work with `BetterRolls5e`. When clicking on an NPC attack (e.g.) I get the standard output in chat (i.e. an Attack and Damage button).

**Comment by RedReign** [comment]
Hey - can you confirm if this issue still exists?

**Comment by geoidesic** [comment]
Confirmed. Still exists.

**Comment by geoidesic** [comment]
Actually I take that back, I got confused. Seems to be working now.
