### ISSUE TITLE
Arrow bonuses are not being added

### ISSUE THREAD

**Issue by carlbutz** [RedReign/FoundryVTT-BetterRolls5e#108]
When I have a +1 arrow or and arrow that does fire damage. Without Better Rolls the to hit and damage bonuses are applied. When run with Better Rolls those bonuses are not applied. I like the ease of use of Better Rolls, but with this limitation it makes it difficult to use. Am I doing something wrong or is this a bug?

**Comment by RedReign** [comment]
Fixed in the next update!
