### ISSUE TITLE
Better Rolls tab no longer appears on Tidy5e item sheets

### ISSUE THREAD

**Issue by joshjlewis93** [RedReign/FoundryVTT-BetterRolls5e#109]
As of Tidy 5e sheets v.0.2.21 with the changes to item sheets, the Better Rolls tab no longer appears on Tidy 5e item sheets. The tab can still be accessed by changing back to the default 5e sheet. Presumably this is because BR only adds it to the default item sheet and Tidy now uses its own version.

**Comment by akrigline** [comment]
A PR into Tidy Sheets has been opened to resolve this. I don't believe any action is required in FoundryVTT-BetterRolls5e

https://github.com/sdenec/tidy5e-sheet/pull/95

**Comment by RedReign** [comment]
This is an issue that has been reworked and resolved as of the 0.7.x database error issue.
