### ISSUE TITLE
Fresh Installs get v1.1.9

### ISSUE THREAD

**Issue by akrigline** [RedReign/FoundryVTT-BetterRolls5e#110]
When starting up my freshly installed dnd5e system (0.96) world with a freshly installed BetterRolls5e (1.1.9) in foundry 0.6.6, I am seeing BetterRolls5e fail to initialize.

![image](https://user-images.githubusercontent.com/7644614/93021794-c0737f80-f5b2-11ea-829d-d2f6e1b3e060.png)

Sure enough when I go into my 5e system files, I see no such file.
![image](https://user-images.githubusercontent.com/7644614/93021828-07fa0b80-f5b3-11ea-9918-e032d982338b.png)

Digging deeper, it seems that the dialog used to confirm spell usage is now a generic usage of the `ability-use-dialog`. Also, strangely, this `SpellUseDialog` imported doesn't seem to be used anywhere in `betterrolls5e.js`.

Tinkering, changed SpellUseDialog to use the "new" AbilityUseDialog and everything seems to work.

**Comment by akrigline** [comment]
Alright. I'm wierded out now. Just cloned this repo and these lines are fixed.

**Comment by akrigline** [comment]
Uninstalling to see if a fresh install helps. I see 1.1.9 as the version I can install, though the [module.json](betterrolls5e/module.json) says 1.1.11

![image](https://user-images.githubusercontent.com/7644614/93022117-37117c80-f5b5-11ea-8ae5-405a18c0e621.png)

**Comment by akrigline** [comment]
Alright, having installed 1.1.9 I clicked Check Update for the fun of it, and sure enough 1.1.11 was delivered:
![image](https://user-images.githubusercontent.com/7644614/93022201-f2d2ac00-f5b5-11ea-9326-9c316980f6ed.png)

**Comment by Jopyth** [comment]
I had the same issue. First the module did not do anything, except add its configuration options. I did not find the error on the console, but it probably was there.

After updating the module I have 1.1.11 now, and it works like a charm.

**Comment by RedReign** [comment]
Hey! Sorry about that. I have resolved this issue. The module browser should list the most recent version as 1.1.11 now.

Thank you all for the report and troubleshooting.

**Comment by Jopyth** [comment]
Thanks for fixing it and thank you for the great module!
