### ISSUE TITLE
Rolling Skill checks before the roll

### ISSUE THREAD

**Issue by Bryn1701** [RedReign/FoundryVTT-BetterRolls5e#112]
As the title says. No matter what settings I make in Better Rolls module, it always seems to roll a skill check before the actual rolls. This goes for skills such as Acrobatics and on ability checks/saves.

**Comment by RedReign** [comment]
I'm not sure I understand. Are you referring to 3d Dice So Nice rolls?

**Comment by Bryn1701** [comment]
Apologies. I should have tested further. It seems to be an issue when Mess - Moerills enhancing super-suit(e) and Better rolls are enabled together. Mess seems to make its own roll before Better rolls. It was a little confusing. Is there a way to correct this without disabling either modules ?

**Comment by RedReign** [comment]
I don't plan on adding support for MESS, as I haven't gotten my hands on it yet. I know you don't want to hear it, but your best solution here is to disable one or the other - having two roll-enhancing suites is bound to cause issues that are very hard to make support for.
As far as I know, you can turn off the part of MESS that rolls items, ability checks, and saves.
