### ISSUE TITLE
versatile damage rolls normal damage

### ISSUE THREAD

**Issue by ParadoxGery** [RedReign/FoundryVTT-BetterRolls5e#113]
it seems like rolling versatile damage rolls the normal damage
this sadly makes me deactivate this module as I need versatile damage to make spellcasters happy

I need a way to have two damage rolls that scale both with spell level and with the vanilla system versatile is the key to happiness
Spells that scale on two rolls:
- Acid Arrow
- Green Flame Blade
- Booming Blade

**Comment by ParadoxGery** [comment]
it seems like `scaleDamage` will overwrite the versatile formular and the regular damage will be scaled instead of the versatile one

**Comment by DrWiFi** [comment]
Toll the Dead is also effected by this. Could there be an attack or spell option to roll both the damage formula and the versatile? That way we can always see both results each time and apply the correct damage.
Thanks!

**Comment by RedReign** [comment]
I have fixed versatile damage usage in 1.1.13. However, versatile replaces the first roll by design - if you want it to roll separately, make a separate damage formula, don't use versatile. Thank you for the report!
