### ISSUE TITLE
Tools not rolling disadvantage/advantage

### ISSUE THREAD

**Issue by krysztalzg** [RedReign/FoundryVTT-BetterRolls5e#114]
FoundryVTT: 0.6.6
DnD5e: 0.96
BetterRolls: 1.1.11
Roll type: Single Roll

When I'm trying to do a check for use of tools, eg. Carpenters Tools, it always rolls one dice, no matter holding ctrl or shift down. If roll type is on `Dual Rolls` it applies modificator correctly.

**Comment by Ikaguia** [comment]
Can replicate.
![image](https://user-images.githubusercontent.com/16377028/102904884-1cbb2a80-4451-11eb-8ea2-326f81837821.png)
Also, the 'better rolls' tabs on those items is blank, may be related?

**Comment by CarlosFdez** [comment]
Can confirm tools not rolling adv/disadv is a problem still on this version, however I'm not getting that error. @Ikaguia that seems to be an error involving resource consumption, can you tell me what tool you rolled to get that error?

**Comment by CarlosFdez** [comment]
@krysztalzg Should be fixed in the latest release. If its not, feel free to post here or create a new issue.
