### ISSUE TITLE
@item.level not reporting correctly in damage formula field

### ISSUE THREAD

**Issue by RulyTafzil** [RedReign/FoundryVTT-BetterRolls5e#116]
First off, LOVE your mod. 

Using stock foundry, I can use the reference @item.level in the damage formula field for spells, and if a spell is upcasted it will use the upcasted value. 

For example, I can set the damage formula for the spell "Spiritual Weapon" as "(floor(@item.level/2))d8+@mod" and when upcasted at lvl 4, it will roll 2d8+mod for damage. 

Using better rolls, the formula will always refer to the original spell level. It does not take the upcasted value into account.

Not a big deal, but it would be great if better rolls could also reference the upcasted item.level value.

**Comment by RedReign** [comment]
Fixed in the upcoming version (v1.2)! Thanks for the report!
