### ISSUE TITLE
Version 1.1.11 compatible with 5e version 0.96?

### ISSUE THREAD

**Issue by SirMoogle** [RedReign/FoundryVTT-BetterRolls5e#118]
Hi there, not a super big issue, but my DM recently updated the 5e ruleset to version 0.96 which fixed some other issues we had, but now it seems like Better Rolls won't function on it. Is this expected? We're still running on Foundry 0.6.6.

**Comment by RedReign** [comment]
It should still work! What specific issues is your DM experiencing?

**Comment by SirMoogle** [comment]
I'm not sure if the settings have reset with the version update, but we can't get instant rolls anymore just by clicking on, for example, skills. Shift-clicking does a standard roll instead of with advantage.

**Comment by RedReign** [comment]
Do you get errors in the console (F12) when you try to roll a skill?

**Comment by SirMoogle** [comment]
I don't get any errors in the console when I just left-click, shift+left click, alt+left click, or ctrl+left click. Interestingly, ctrl+left click rolls for disadvantage and alt+left click rolls for advantage. I am assuming that shift may be the alternative roll.

**Comment by RedReign** [comment]
It sounds like your DM is either using a sheet that doesn't support Better Rolls, or BR is simply not enabled. do you have screenshots of your chat output, item sheet, or module list?

**Comment by SirMoogle** [comment]
I've got the [active module list](https://imgur.com/a/vVXTkNa); it seems that we have _updated to Better Rolls 1.1.9_. I'm not sure if that has anything to do with it. There's also Magic Items present, but I don't think Better Rolls would conflict with that? It doesn't appear to have done so in the past.

A module that should be inactive is the Macro Toolbar, but it still works. If I try to drag a spell onto the macro toolbar now it fires as if there were no modules (i.e., item card appears in chat, have to click to roll for damage and hit separately). Trying to use a macro that was created before we switched over gives this console error:

    ReferenceError: BetterRolls is not defined
      at Macro.eval (eval at callScriptMacroFunction (Macros.js:176), <anonymous>:5:17)
      at Macro.callScriptMacroFunction [as callScriptFunction] (Macros.js:179)
      at Macro.renderMacro [as renderContent] (Macros.js:197)
      at Macro.executeMacro (Macros.js:221)
      at Hotbar._onClickMacro (foundry.js:21674)
      at HTMLLIElement.dispatch (jquery.min.js:2)
      at HTMLLIElement.v.handle (jquery.min.js:2)

**Comment by RedReign** [comment]
Make sure to update to 1.1.11. It contains a lot of fixes.

**Comment by SirMoogle** [comment]
Alright, everything seems to be back to normal; guess it was just version error on our side; thanks for hashing this out.
