### ISSUE TITLE
window.BetterRolls is undefined when module tries to register actor sheet

### ISSUE THREAD

**Issue by akrigline** [RedReign/FoundryVTT-BetterRolls5e#122]
## Problem
```js
Hooks.once('ready', function () {
  log('ready', { window: window.BetterRolls });

  // register this sheet with BetterRolls
  if (window.BetterRolls) {
    log('ready and BetterRolls exists');
    //@ts-ignore
    window.BetterRolls.hooks.addActorSheet('OGL5eCharacterSheet');
  }
});
```
Logs `window: undefined` if by chance your module's `ready` hook fires before BetterRolls' does. These appear to fire alphabetically, since my module `5eOGLCharacterSheet` has this issue but `CompactBeyond5eSheet` does not.

## Proposal

Fire a custom hook `BetterRollsAddedToWindow` after BetterRolls adds its hooks to the `window` which other modules can hook into reliably.

**Comment by RedReign** [comment]
See the response I posted in the pull request. Thank you for the report and the contribution, though!
