### ISSUE TITLE
Add quick roll option to toggle on/off consuming spell slots

### ISSUE THREAD

**Issue by schultzcole** [RedReign/FoundryVTT-BetterRolls5e#124]
Currently, you can toggle on or off whether a quick or alt roll for an item consumes the associated charge or resource, but you can't change whether it consumes a spell slot or not. Having this option could be useful for spells where you might roll attack/damage multiple times for a single casting of the spell.

For instance scorching ray, you might set it up so the normal roll consumes a spell slot and rolls for the first ray, while an alt roll could be set up to just roll the attack and damage, but not consume a spell slot, so that the second and third rays can be cast without needing to worry about unchecking the consume spell slot button.

One complication I foresee is what should happen in the case where the spell was upcast. For that case, maybe users will just have to revert to the previous workflow of unchecking consume spell slot in the dialog.

**Comment by RedReign** [comment]
Duplicate of #101

**Comment by schultzcole** [comment]
Ah, sorry about that. I looked for an existing issue but apparently I'm not good looking enough 😉 

I'll close this issue then.
