### ISSUE TITLE
getActorByName fails when a token of the specified name is not on the canvas

### ISSUE THREAD

**Issue by Pjb518** [RedReign/FoundryVTT-BetterRolls5e#129]
The intention is that if the actor can't be found on the canvas, the function falls back to the source actors, but a `TypeError` occurs before we can reach that fallback.

Here is the current function implementation:

```js
function getActorByName(actorName) {
    let actor = canvas.tokens.placeables.find(p => p.data.name === actorName).actor;
    if (!actor) actor = game.actors.entities.find(e => e.name === actorName);
    return actor;
}
```

Because the [`find` method returns `undefined` in the event that a matching element can't be found](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find#Return_value), we end up trying to access the `actor` attribute on the `undefined` property on this first line. Naturally this doesn't exist, so we get a `TypeError`.

I noticed the issue while trying to run one of my macros without a token on the canvas, as some of my code wasn't executing. I'm sure there are other parts of the module which are breaking under similar conditions.

Changing to something like this would fix the problem, I believe:

```js
function getActorByName(actorName) {
    const actorToken = canvas.tokens.placeables.find((p) => p.data.name === actorName);
    const actor = actorToken
        ? actorToken.actor
        : game.actors.entities.find((e) => e.name === actorName);

    return actor;
}
```

**Comment by RedReign** [comment]
Thanks for the report! I think I'll simply use optional chaining:
`function getActorByName(actorName) {
    let actor = canvas.tokens.placeables.find(p => p.data.name === actorName)?.actor;
    if (!actor) actor = game.actors.entities.find(e => e.name === actorName);
    return actor;
}`

**Comment by RedReign** [comment]
Yep, that seems to do it (you may notice I already had the `?` optional chaining in `getActorById()`) in the next update! Thanks again for the report.

**Comment by Pjb518** [comment]
No problem!

I avoided optional chaining, just because of the lower browser support, but I guess it really doesn't matter in this case. If your browser doesn't support optional chaining, Better Rolls not working is likely the least of your problems with Foundry haha.
