### ISSUE TITLE
Unable to pop-out chat messages originating from BetterRolls in 0.7.x

### ISSUE THREAD

**Issue by archeresky** [RedReign/FoundryVTT-BetterRolls5e#138]
Environment: self-hosted node.js
Browser: Firefox
FoundryVTT: 0.7.5
DnD5e: 0.98
BetterRolls: 1.1.17
Roll type: Dual Rolls

0.7.x introduces feature to pop-out chat messages by right-clicking the message and choosing the pop-out button which is especially useful in situations where you have to roll multiple Save DCs and apply damages based on the roll. However, messages originating from BetterRolls lack this functionality, after right-clicking the message coming from the module, the button to pop-out message is missing.

**Comment by Ktar5** [comment]
Same issue with:
Environment: Normal downloaded one
Browser: Foundry application
FoundryVTT: 0.7.8
DnD5e system: 1.1.1
Better Rolls: 1.2.1

I also encounter this issue where BetterRolls chat messages do not pop out, and other context actions are also missing. See the attached screenshots.


Default sheet roll with BetterRolls5e enabled
![Default sheet roll with BetterRolls5e enabled](https://i.imgur.com/mAL2syY.png)

BetterRolls5e roll
![BetterRolls5e roll](https://i.imgur.com/kllEeu9.png)

Damage roll with BetterRolls5e *disabled*
![Default damage roll](https://i.imgur.com/b9KhCkQ.png)

Damage roll with BetterRolls5e *enabled*
![Damage roll with better rolls 5e enabled](https://i.imgur.com/74EcI5O.png)

**Comment by RulyTafzil** [comment]
I'm experiencing the same behavior. Would like to know if a change in planned? or perhaps is not possible w/o significant work?

**Comment by CarlosFdez** [comment]
Nothing planned, but I'll look into it at some point. Would be in the development branch if it happens. I looked into see if core.canPopout makes it work and while it kinda works, it doesn't seem to update when the chat content updates causing problems with the new damage button feature:

![image](https://user-images.githubusercontent.com/1286721/104111885-c0139880-52b5-11eb-8675-7a471f1304c0.png)

Would need some assistance with that matter.

**Comment by CarlosFdez** [comment]
@RulyTafzil @archeresky @Ktar5 So reported it and Atropos has confirmed not re-rendering as a bug in Foundry. So I'll include pop out when I start on reroll card functionality, and look into how the context actions actually work into everything.

**Comment by CarlosFdez** [comment]
Implemented it for the newest alpha version. Note that roll edit options don't re-render popped out messages for the current version of Foundry.

@Ktar5 You may have realized after all this time passed, but I think the reason its inconsistent is that you may not have tokens selected. The overlay menu on BR and the deal damage options for vanilla 5e rolls (like the ones you're showing) both do not show if there are no tokens selected.
