### ISSUE TITLE
Make Item Image Auto-Roll in Firefox

### ISSUE THREAD

**Issue by novabuckeye** [RedReign/FoundryVTT-BetterRolls5e#14]
I'm unable to use the Make Item Image Auto-Roll in my instance using Firefox.  The feature works in Chrome for my instance.

When trying to roll a spell, item, or feature in Firefox I get the following error:
`TypeError: window.Components.getComponentHtml is not a function` on custom-roll.js:559

Any idea what could be causing this? I've tried uninstalling and reinstalling the module. I've also tried in a fresh world with no other modules installed.

**Comment by RedReign** [comment]
Thanks, fixed in the next update!

**Comment by novabuckeye** [comment]
That worked perfectly, thanks!
