### ISSUE TITLE
Placement Template Issue

### ISSUE THREAD

**Issue by NukeMaster0** [RedReign/FoundryVTT-BetterRolls5e#141]
There is support for "Minor Quality of Life Improvements" with this module, however, when I want a weapon, say a Grenade to explode and deal damage with the template automatically, a template will not appear, opening up the weapon's page and clicking the tab called "Better Rolls" I see there is an option to select "Place Template", but when I clicked it and tried again I noticed it did not work or even gave me an option to do so. I tried with and without MQOFI and nothing worked.

**Comment by figotech** [comment]
Would it be possible to add an option to always show the "place template" button on the card where the dice where rolled? That way if something fails you can still try to place the template again and let Midi-Qol do the rest
