### ISSUE TITLE
versatile dmg in spells not working

### ISSUE THREAD

**Issue by ParadoxGery** [RedReign/FoundryVTT-BetterRolls5e#143]
Foundry: 0.7.5
DND: 0.98
BetterRolls5e: 1.1.17

Steps to reproduce:
1. create a spell
2. set a formular to first dmg and a different to versatile
3. roll without versatile set in config
4. roll with versatile set in config
5. notice it will be the same formular but with the "(versatile)" message

**Comment by ParadoxGery** [comment]
use case:
Toll the Dead
> 1d8 necrotic damage. If the target is missing any of its hit points, it instead takes 1d12 necrotic damage.
so I would set up 1d8 for normal dmg and 1d12 as versatile
then I set the normal roll to no versatile and the alt roll to versatile

just as a note: I find it strange that I have to check the normal dmg if I just want the versatile one

**Comment by BastianClarenbach** [comment]
Bumping this. Versatile dmg works fine with items, but fails on toll the dead. Please fix!

**Comment by CarlosFdez** [comment]
Looking into this now for the alpha version, but heads up: versatile damage would still use the main scaling. So at level 11 it'd be 1d8+2d12. You'll have to remove scaling and handle it manually.

**Comment by CarlosFdez** [comment]
Done, fixed in this branch. But careful with what I mentioned. You might need some trickery to get scaling to work https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/tag/v1.2.alpha.7
