### ISSUE TITLE
Doesn't allow item from being destroyed

### ISSUE THREAD

**Issue by Kekilla0** [RedReign/FoundryVTT-BetterRolls5e#15]
For some reason the module doesn't allow the item from being destoyed once its last charge/use has been used. Noticed the problem when using a Potion of Healing and it allows you to indefinetly use it instead of destroying it once it becomes 0/1.

**Comment by DarKDinDoN** [comment]
Noticed that line 447 of file custom-roll.js is commented out. Might be this?
Didn't test all items (spells, feats, etc.), but it seems to be working if I uncomment this line.

**Comment by RedReign** [comment]
Thanks, implemented in the next update!
