### ISSUE TITLE
Cantrip Scaling doesn't work past Level 5

### ISSUE THREAD

**Issue by Meneltamar** [RedReign/FoundryVTT-BetterRolls5e#151]
With BR enabled, cantrip damage doesn't scale past character level 5. Even if the character is > level 15, it only rolls for example 2d10 for Fire Bolt.

**Comment by ervwalter** [comment]
In fact cantrip scaling is broken completely and always rolls 2 dice.  I'm submitting a PR with the fix now.  It's a one line change if you want to change it yourself while waiting for the PR to get merged and released.

**Comment by CarlosFdez** [comment]
Fixed in newer releases!
