### ISSUE TITLE
Support the Skill Customization for D&D 5e Mod

### ISSUE THREAD

**Issue by Sky-Captain-13** [RedReign/FoundryVTT-BetterRolls5e#158]
https://foundryvtt.com/packages/skill-customization-5e/

Better Rolls only looks for the total skill modifier which means we can't put 1d4 into the skill mod field for things like the dragonmark feats from Eberron.

**Comment by CarlosFdez** [comment]
Supported now in that there alpha branch, as you already know from that there discord, so closing the ticket.
