### ISSUE TITLE
3d Dices :)

### ISSUE THREAD

**Issue by trotroyanas** [RedReign/FoundryVTT-BetterRolls5e#16]
Hi,
possible BetterRolls5e support **3D Dices** ?

**Comment by RedReign** [comment]
Hey,
At the moment they support just the first die roll on the d20, but soon all dice will be thrown.

**Comment by Noggin01** [comment]
Will there be an option to delay displaying the results until the dice complete their roll? This is a deal breaker for my players, they need the suspense. They won't go for instant results.

**Comment by RedReign** [comment]
I hope to implement that as the baseline functionality.

**Comment by RedReign** [comment]
Added to 1.1.2!
