### ISSUE TITLE
Cantrip Level scaling not working

### ISSUE THREAD

**Issue by Cryover** [RedReign/FoundryVTT-BetterRolls5e#160]
Tested in dnd5e 0.98
FoundryVTT 0.7.5
BetterRolls 1.1.17

BetterRolls doesn't recognize the @details.level of the character when scaling cantrips. This problems does not happen when using default roll when casting cantrips.

Example: characters in any level will always have the level 5 cantrip scaling no matter their current level.

**Comment by DandDPM** [comment]
I have also verified this bug on 0.7.5

**Comment by oestred** [comment]
Confirmed the same, on 0.7.5

**Comment by RedReign** [comment]
Fixed in 1.2.0
