### ISSUE TITLE
Spells with slots and rolls not working

### ISSUE THREAD

**Issue by MrSumOne** [RedReign/FoundryVTT-BetterRolls5e#161]
I found that when I cast a spell that include a spell slot and a roll don't do anything when I click on the roll button. It consumes the spell slot but nothing appears in chat and no rolls are made. In the console I see the error:

`Uncaught (in promise) TypeError: Cannot read property 'quickDamage' of undefined
    at CustomItemRoll.rollDamage (custom-roll.js:1222)
    at CustomItemRoll.fieldToTemplate (custom-roll.js:621)
    at custom-roll.js:703`

I found a way to fix it. If you open the "Edit Item" and then close it, the spell starts to work again. This has to be done for every spell that doesn't work. Everything works correctly when BR is turned off.

**Comment by Cryover** [comment]
I also have this problem. It seems that changing the action type to any other fix the issue. After you changed you can put the one that was before.

**Comment by warfric** [comment]
I third this issue. It seems it can be fixed by simply clicking the "edit" button on the malfunctioning spell then closing the edit window, then re-rolling the spell. But this is annoying.

**Comment by Rencos1** [comment]
To fix this issue, replace 	flags = itm.data.flags.betterRolls5e by this.itemFlags.betterRolls5e at line 1156 in custom-roll.js.
When await actor.update({ [`data.spells.${spellSlot}.value`]: Math.max(parseInt(actor.data.data.spells[spellSlot].value) - 1, 0)}); resolved, the flags are reset.

**Comment by tulku** [comment]
@Rencos1 could you provide a diff with your path?

**Comment by Rencos1** [comment]
It is in this function in custom-roll.js. When the spell count is updated in the actor. The flags are resets so itm.data.flags is empty when rollDamage is resolved. I don't know why the flags are reset when a value is changed in the data object. But there is a copy available with itemFlags with the original flags.
	async rollDamage({damageIndex = 0, forceVersatile = false, forceCrit = false, bonus = 0, customContext = null}) {
		let itm = this.item;
		let itemData = itm.data.data,
			rollData = duplicate(itm.actor.data.data),
			abl = itemData.ability,
			**flags = itm.data.flags.betterRolls5e,** // To replace by **flags = this.itemFlags.betterRolls5e,**
			damageFormula,
			damageType = itemData.damage.parts[damageIndex][1],
			isVersatile = false,
			slotLevel = this.params.slotLevel;

**Comment by CarlosFdez** [comment]
I believe this is fixed now, so please make a new issue if its still broken.
