### ISSUE TITLE
Set a Flag on Better Rolls ChatMessage

### ISSUE THREAD

**Issue by mesfoliesludiques** [RedReign/FoundryVTT-BetterRolls5e#163]
Hi, 
I am working on compatibility with Bubble rolls.
I don't have any solid way of knowing the ChatMessage is generated by BetterRolls so I can't decide how to render it.
Could you set a flag in the Message Data ?

**Comment by CarlosFdez** [comment]
I think this will probably happen on its own to support certain future features, but as a heads up the content has a red-dual class you can use to check that it was created by Better Rolls.

**Comment by CarlosFdez** [comment]
This is now something handled in the development branch (as of alpha releases). For current versions checking the content for the red-dual css class is the way to go.
