### ISSUE TITLE
1.2.2 and 1.2.3 Modules not loading / working

### ISSUE THREAD

**Issue by AnEnemyChampion** [RedReign/FoundryVTT-BetterRolls5e#178]
After updating to 1.7.9 the following versions of BetterRolls do not work:
 - 1.2.2: https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/download/v1.2.2/module.json
 - 1.2.3: https://raw.githubusercontent.com/RedReign/FoundryVTT-BetterRolls5e/master/betterrolls5e/module.json

However, the previous 1.2.0 version does work:
 - 1.2.0: https://raw.githubusercontent.com/RedReign/FoundryVTT-BetterRolls5e/v1.2.0/betterrolls5e/module.json

By **Not Work** I mean:
 - The module DOES show up in the Add-On Modules folder in the Setup screen of foundry
 - The module does NOT show up in the in-world "Manage Modules" or "Configure Settings" menus
 - The module does NOT show up as an option for Token Action HUD to utilize it
 - The module does NOT function as it normally would with regard to holding shift, ctrl, or alt on skills, abilities, etc. ; instead, they work the default foundry way.
 - Macros that are made by drag-dropping features to the toolbar will show the default foundry scripts instead of BetterRolls.quickRollById codes.

To reproduce the error:
 - Use Foundry 1.7.9
 - Download the add-on through the manifest URLs I have provided in this issue report ( i.e https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/download/v1.2.2/module.json )
 - Launch a world and click "Manage Modules" from the Game Settings menu.

**Comment by CarlosFdez** [comment]
Have you made sure the DND system was updated? The module not showing happens when the system does not match the minimum version.

**Comment by AnEnemyChampion** [comment]
That resolved it. Thank you.
