### ISSUE TITLE
Finesse Property not being applied unless weapon has been edited (i.e. from compendium)

### ISSUE THREAD

**Issue by wleung85** [RedReign/FoundryVTT-BetterRolls5e#179]
**Tested on:**
Foundry v0.7.7
DnD5e v1.2.0
BetterRolls v1.2.2 and v1.2.3

**Description:**
When importing weapons from compendiums (e.g. from the SRD compendiums included with DnD5e), the attack and damage rolls do not account for the finesse property by default. For example, using a Dagger will roll with Str and not the higher Dex modifier. If the item's edit dialog is opened up at least once, the subsequent rolls factor Finesse correctly and use the correct modifier.

**Steps to reproduce:**
1. Have a character with a higher Dex modifier than Str
2. Import a Dagger (or any finesse weapon like Rapier) to the character from the Items (dnd5e) compendium provided by the game system
3. Do a quick roll with the weapon. Opening the roll calculations will show it's using the Str modifier instead of Dex.
4. Open and close the weapon's edit dialog
5. Do another quick roll with the weapon. Opening the roll calculations will show it's now correctly using the Dex modifier. This should be the default behaviour already.

**Example:**
In the following attached video, I demonstrate and reproduce this problem. The character's str modifier is +0 compared to the dex modifier of +5. I also disable the BetterRolls module at the end and roll with the basic 5e roller to demonstrate that the issue isn't present there, and is specific to the module.

https://user-images.githubusercontent.com/16823748/103112407-4166fc00-4623-11eb-9a48-782c30b7d6ea.mp4

**Comment by CarlosFdez** [comment]
Did a quick test and can confirm it is the case in the release version, but it was fixed in the alpha version. This fix seems to have happened accidentally so I'll dig a bit deeper later. Thanks for posting this.

**Comment by CarlosFdez** [comment]
I got curious so I dug in quicker than I did and found the cause. That said, all roll formula stuff has been consolidated (refactored) in the development branch, so its very unlikely I'll be touching any older calculation stuff unless there's severe bugs with it.

https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/tag/v1.2.alpha.5 for dev version stuff. Otherwise you can tinker with item settings in the meantime to get stuff straightened out.

**Comment by wleung85** [comment]
Thank you for the quick response. I'll close the ticket with the next official release

**Comment by wleung85** [comment]
I've tested this on the latest official release version 1.3.1 and can confirm the issue is resolved.
