### ISSUE TITLE
Exception in custom-roll.js

### ISSUE THREAD

**Issue by KageJittai** [RedReign/FoundryVTT-BetterRolls5e#18]
When making a saving throw with the default mystery man icon, custom-roll.js throws an exception and no rolls are made.

Exception:

`Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at Function.fullRollAttribute (custom-roll.js:196)`

Line which blows up:

`		let titleImage = ((actor.data.img == DEFAULT_TOKEN) || actor.data.img == "" || actor.data.img.includes("*")) ? actor.token.data.img : actor.data.img;
`

**Comment by RedReign** [comment]
Fixed in the next update! Thank you for the report.
