### ISSUE TITLE
Module not appearing in my 5e game

### ISSUE THREAD

**Issue by rahcek** [RedReign/FoundryVTT-BetterRolls5e#182]
I have checked that the module is on the latest version, tried deleting and reinstalling it, and it is still not in the list under "manage modules" or in "module settings".
![image](https://user-images.githubusercontent.com/76706732/103241481-442b5f00-494b-11eb-8563-26fe071e86e5.png)
![image](https://user-images.githubusercontent.com/76706732/103241494-4c839a00-494b-11eb-8d5f-9c9eebb37647.png)

**Comment by rahcek** [comment]
The module was working until I updated everything after a break last night. I can't live without it!

**Comment by ajclarke90** [comment]
Also having this issue! Not played for a few weeks with Chistmas though

**Comment by TNychka** [comment]
Hey @rahcek and @ajclarke90! 
So I dug into it and figured out the problem (for me at least). The latest Better Rolls requires DnD 1.2.0. It will fail silently (which seems to be a problem inherent to foundry, not this module) if you aren't on the latest.
Try updating to see if that works!

**Comment by ajclarke90** [comment]
Can confirm that this solves the issue. Shame it fails quietly, I might see if I can ping a suggestion to the Foundry devs. I'd been putting off upgrading DND5E as I know sometimes it breaks module compatibility until devs have chance to fix.
