### ISSUE TITLE
Crits not using meleeCriticalDamageDice setting

### ISSUE THREAD

**Issue by Nonstick-Panda** [RedReign/FoundryVTT-BetterRolls5e#183]
When setting an additional melee critical damage dice under Special Traits, BetterRolls5e still only rolls 1 dice for the crit roll.  Confirmed disabling BetterRolls5e works fine, I assume the issue is an interaction with the crit settings specific to BetterRolls5e as it seems that crit threshold is used, just not the damage dice setting.

EDIT: Not too familiar with GitHub, but it seems like this is actually an extremely easy fix since there's already code to account for the Savage Attacks flag, which is stored in the same area.  In custom-roll.js, lines 1166-1177, if you replace with the below, allows this function to work:
```
let critBonusDie;

// If the crit formula has no dice, return null
if (critRoll.terms.length === 1 && typeof critRoll.terms[0] === "number") { return null; }

if (itm.data.type === "weapon") {
	try { critBonusDie = itm.actor.getFlag("dnd5e", "meleeCriticalDamageDice") || 0; }
	catch(error) { critBonusDie = itm.actor.getFlag("dnd5e", "meleeCriticalDamageDice") || 0; }
}
let add = (itm.actor && critBonusDie) ? critBonusDie : 0;
critRoll.alter(1, add);
critRoll.roll();
```

**Comment by CarlosFdez** [comment]
@Nonstick-Panda  did a fix in the development branch. If you're willing to use not-fully tested releases, you can use that one. So long as there are a few days before your next session it should be fine to use.

https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/tag/v1.2.alpha.6

Let me know if you run into any problems with it. Unfortunately anything involving roll calculation has already deviated quite a bit.

**Comment by CarlosFdez** [comment]
I just saw you PR'd on my own repo. I'm a bit ashamed I didn't notice until after I already did this. Currently the refactor is in the development branch of this repository.
