### ISSUE TITLE
Doesn't show Save DC button when Action Type is not Saving Throw

### ISSUE THREAD

**Issue by 9ryex5** [RedReign/FoundryVTT-BetterRolls5e#184]
As you can see in the Image, if the attack is of type Saving Throw, you can see you Save DC button in chat as expected.
But if the attack is of type Melee Weapon Attack and has a Saving Throw (like Bite), you can't see Save DC button in chat.

![image](https://user-images.githubusercontent.com/43207603/103328333-6d81e300-4a50-11eb-8b83-d85d1894e96b.png)

**Comment by Nonstick-Panda** [comment]
It doesn't automatically, but if you go to the Better Rolls tab on the item, you can enable the Save DC checkbox there and it will show.

![image](https://user-images.githubusercontent.com/76752796/103365103-51506700-4a8d-11eb-935b-27cb4ac7bdc7.png)

![image](https://user-images.githubusercontent.com/76752796/103365117-5b726580-4a8d-11eb-8cd0-6ac0f759b882.png)

**Comment by CarlosFdez** [comment]
Save DCs are now enabled in weapons by default in v1.3.1. While in some cases it might be better to do Description+SaveDC in the alt roll, if this is off by default it does cause some confusion, so there it is.

Thanks for asking about this.
