### ISSUE TITLE
Request: Do not automatically roll damage

### ISSUE THREAD

**Issue by weihanderz** [RedReign/FoundryVTT-BetterRolls5e#185]
It would be nice to be able to roll damage in card for purposes of giving players the opportunity to reactions such as uncanny dodge and shield without knowing how effective the damage is.

**Comment by Nonstick-Panda** [comment]
If you check under the Pull Requests tab on this page, you'll see a link for a WIP alpha version that has this exact feature:

https://github.com/RedReign/FoundryVTT-BetterRolls5e/pull/169

**Comment by weihanderz** [comment]
Oh, didn't see that. Thank you. Closing ticket.

**Comment by CarlosFdez** [comment]
That one is actually out of date. I made a new PR from the dev branch with the actually up to date version.
You can also dig in the releases for those that say alpha.

https://github.com/RedReign/FoundryVTT-BetterRolls5e/pull/186

**Comment by weihanderz** [comment]
Thanks for the update! The alpha one seems to erase the entire roll card whenever it tries to edit/replace the card (rolling advantage/disadvantage, rolling for damage button, improving damage to crit button). I hope it's just me and there's something I can do to fix it. These new features are awesome!

**Comment by weihanderz** [comment]
Figured it out. It actually works fine except when using the tabbed chatlog module.

**Comment by CarlosFdez** [comment]
I should look into the tabbed chatlog module then. Thank you for the report!
