### ISSUE TITLE
ignoring spellCriticalThreshold flag of dnd5e for ranged spell attacks

### ISSUE THREAD

**Issue by Stendarpaval** [RedReign/FoundryVTT-BetterRolls5e#187]
I've made a macro for my warlock player to make Hexblade's Curse easier to use. One of the things it does is change the weaponCriticalThreshold and spellCriticalThreshold flags from 20 to 19. For clarity I've included the macro here: 

[hexbladesCurse.txt](https://github.com/RedReign/FoundryVTT-BetterRolls5e/files/5757719/hexbladesCurse.txt)

If the warlock's character attacks with a weapon attack, everything works as intended: he crits at 19 or 20. However, if he uses Eldritch Blast (which is like 90% of what he does) then his ranged spell attack rolls are only considered critical when a 20 is rolled. This happens despite the spellCriticalThreshold value in the Special Traits page showing it at 19. 

I've deactivated all modules and experimented with this to find the cause of it. It turns out that Core Foundry *does* register crits at 19 or 20 for ranged spell attacks. Only when I activate Better Rolls 5e does it stop working. By the way, this doesn't just happen for cantrips like Eldritch Blast, but also for spells of 1st level or higher that require ranged spell attack rolls such as Scorching Ray.

My temporary fix is for that character to change the attack type of these spells from Ranged Spell Attack to Ranged Weapon Attack. This isn't the prettiest solution, but it works well. 

Before I forget: I'm on Foundry VTT version 0.7.9, running Better Rolls 5e version 1.2.3.

**Comment by CarlosFdez** [comment]
So Better Rolls does support crit thresholds, but they're tied to items. Wasn't aware DND had those properties globally. Will look into implementing them on the alpha branch that's in progress.

**Comment by CarlosFdez** [comment]
@Stendarpaval did a fix in the development branch. If you're willing to use not-fully tested releases, you can use that one. So long as there are a few days before your next session it should be fine to use.

https://github.com/RedReign/FoundryVTT-BetterRolls5e/releases/download/v1.2.alpha.6/module.json

Let me know if you run into any problems with it.

**Comment by Stendarpaval** [comment]
Sorry for the late response, thank you for making a fix! Since I have two sessions coming up (one tomorrow night, and one the night after) I will wait until after these sessions to check out the alpha build. I'll let you know if I run into any problems with it then.

**Comment by Stendarpaval** [comment]
So I finally got around to installing the alpha build (currently on foundry Core v0.7.9, dnd5e v1.2.2 and Better Rolls for 5e v1.2.alpha.13) and everything seems to be running smoothly. No issues so far with the 41 other modules that are active. 

I tested the weapon & spell attack crit thresholds for that Eldritch Blast user I described above, and after changing the attack type back to Ranged Spell Attack that character is still able to crit on a 19 or higher while using Hexblade's Curse. 

Thanks for your hard work maintaining and even further improving this module! The ability to see the roll result before bonuses quickly (without clicking) is sure to speed up our combat in the future, as well as debugging any changes I made to new items. Really nifty! It looks rather polished, as well. 

Anyhow, this issue seems resolved from my point of view, so I'll close it.

**Comment by CarlosFdez** [comment]
Thanks for looking into it! alpha 13 is very likely to be stable, and I think the only feature missing that I'd like to add is re-rolling attacks without consuming resources (for stuff like scorching ray/spirit guardians). Fingers crossed though.

New version should also make it easier to write macros and evaluate results, even wrote a defensive flourish macro for it that creates an AC boosting active effect to test it out.
