### ISSUE TITLE
Possible incompatibility with character sheets

### ISSUE THREAD

**Issue by SirMoogle** [RedReign/FoundryVTT-BetterRolls5e#188]
Currently using BetterRolls5e version 1.2.0, and also have Token Action HUD (version 0.9.23) and Tidy5e Sheet (version 0.3.5) active. For some reason, holding Shift or Ctrl when trying to roll for a saving throw or skill does not work on the character sheet's attributes page (no prompting for rolling for advantage/disadvantage either; just a straight roll). Rolling for attacks from the inventory or spellbook appear to be working as usual, and holding Shift and Ctrl work when selecting items from the Token Action HUD menu. Do you see any potential conflicts here? If requested I can try and post the full module list here.

**Comment by CarlosFdez** [comment]
Even on the newest live release it seems that bug still exists, though its been fixed in the alpha version.

**Comment by SirMoogle** [comment]
That's unfortunate to hear. I guess I'll wait until the new version pops out of alpha, then.

**Comment by CarlosFdez** [comment]
As a heads up, the alpha release has already released, have you tried updating?

**Comment by SirMoogle** [comment]
Ah, my DM updated it. The trouble shifted over to the Token Action HUD, but I think that was fixed with an update on that end.
