### ISSUE TITLE
Disadvantage rolls should not show crit damage when (kept) lower die does not crit

### ISSUE THREAD

**Issue by Lazytron** [RedReign/FoundryVTT-BetterRolls5e#19]
Currently if either die crits on a disadvantaged roll, crit damage is shown. Crit Damage should only show on a disadvantaged roll if the kept die crits.

**Comment by RedReign** [comment]
I would like to keep the crit damage available, just in case a DM decides that critical damage should be used (or the disadvantage should be negated) after the dice were rolled.

**Comment by AterIgnis** [comment]
Sounds more like toggleable setting, then. Having "dmg + critdmg" messages obviously might confuse people in thinking all this damage is to be applied to target, especially people who are new to the game system and/or VTT.
