### ISSUE TITLE
1.2.alpha.9 Auto-roll not functioning

### ISSUE THREAD

**Issue by Zamrod** [RedReign/FoundryVTT-BetterRolls5e#190]
When midi-qol is set to auto roll damage, the damage doesn’t get auto rolled in alpha 9. This is even if “don’t auto roll damage” is turned off in the settings. Because damage is not rolled automatically, it is not applied to the target, even if rolled manually.

**Comment by Zamrod** [comment]
Actually, this is a bigger issue than just midi-qol. The render damage button in chat card and the don’t automatically roll damage settings do not function at all, even with midi-qol disabled.

**Comment by CarlosFdez** [comment]
oh, that's a regression. Thanks for reporting, I'll look into it soon. Most testing I've done recently is with damage prompt on so maybe I broke something.

**Comment by CarlosFdez** [comment]
Just fixed it. Let me know if there's still problems.

**Comment by CarlosFdez** [comment]
Gonna assume its fixed by now. Open a new issue if it happens again!
