### ISSUE TITLE
Possible incompatibility with Active-Auras

### ISSUE THREAD

**Issue by zacdemon** [RedReign/FoundryVTT-BetterRolls5e#191]
There seem to be some incompatibilities with Active-Auras. I haven't had a chance to thoroughly test them so I'm not sure if this is on your end or Kandashi's so I figured I would alert you both. I tested this with the Aura of Devotion demo in Active-Auras' Readme. The Aura seems to behave as indented for tokens other then the carrier, but for the token carrying the aura when a roll is made I receive this error. It seems to behave as intended when BetterRolls is disabled.
![image](https://user-images.githubusercontent.com/22028379/104107335-57162b80-5289-11eb-9fe4-334debea3836.png)

**Comment by CarlosFdez** [comment]
Hey, thanks for reporting! This fails in the alpha version as well? If so I'll start looking into it tonight.

**Comment by zacdemon** [comment]
I downloaded the Devolvement branch to test the issue there, and it seems to resolved there. I did run into two new issues on that branch though . The first being that rolls from weapons will not auto roll damage even when I have the setting unchecked unless the attack was a critical hit. The second being is that when I roll saving throws in one of my worlds I get this error. 
![image](https://user-images.githubusercontent.com/22028379/104108899-8d0ddc80-5296-11eb-847b-c6b7af90d257.png)
Other worlds seem to work fine though so this could be on my end. Either way this issue is resolved.

**Comment by CarlosFdez** [comment]
The not autorolling bug will be fixed tonight (that's a regression, big oopsie), but that altKey error might be a module incompatibility. I'm assuming that a module you have is overwriting the built in rollAbilitySave() function inherit into DND, and changed the method signature such that it no longer returns a result. The newer betterrolls use the built in dnd rolling functions for actor rolls as does midi-qol.
