### ISSUE TITLE
1.2.alpha.9 When rolling attacks, damage is not automatically rolled unless its a crit

### ISSUE THREAD

**Issue by zacdemon** [RedReign/FoundryVTT-BetterRolls5e#192]
Even when the "damage prompt in chat card" setting is left unchecked, attack rolls and spells will continue to place the damage prompt in the chat card unless the attack is a critical hit.
![image](https://user-images.githubusercontent.com/22028379/104109153-fbec3500-5298-11eb-8cf6-c90468582b26.png)

**Comment by CarlosFdez** [comment]
This was mentioned in #190. Gonna say when its fixed there.
