### ISSUE TITLE
Better Rolls not showing in Foundry 0.7.9

### ISSUE THREAD

**Issue by dzuitaa** [RedReign/FoundryVTT-BetterRolls5e#194]
Hello here, I updated my Foundry to 0.7.9 and now the addon it´s nos showing in my world. I have reinstalled the addon a couple of times and no luck.
Hopefully, there's a way to make this work.
Thanks.

**Comment by CarlosFdez** [comment]
@dzuitaa Update DND 5e in the systems section

**Comment by dzuitaa** [comment]
Great thanks!
