### ISSUE TITLE
[DAE conflict] Some bonus are not applied to rolls

### ISSUE THREAD

**Issue by Angor-de-Redjak** [RedReign/FoundryVTT-BetterRolls5e#196]
Hello!

I just found a compability issue between BR5 et DAE using Find the Culprit.
DAE allow tweaking some parameters like data.bonuses.heal.damage enabling to add a value to all your heal rolls.

The problem is, BR5 doesn't add those bonus. Could you take a look, if you have time?

![ss+(2021-01-09+at+07 30 03)](https://user-images.githubusercontent.com/45643509/104794944-514da800-57ab-11eb-8922-b30c240a5bc1.jpg)

FVTT : 0.7.9

D&D5E : 1.2.2

DAE : 0.2.33

Thank you!

**Comment by gohma231** [comment]
I had this same issue with bonuses applied to saving throws! I can provide more details later.

**Comment by CarlosFdez** [comment]
@Angor-de-Redjak @gohma231 have you tried the alpha version in releases? I recall fixing this particular property in that version.

**Comment by Angor-de-Redjak** [comment]
Absolutely not, I'm with 1.2.3.
I just tried your alpha the problem is no more.
Thank you very much!

**Comment by CarlosFdez** [comment]
Actually, good timing, decided to release. If you press the update button, it should auto-update to the live version too.
