### ISSUE TITLE
Option/setting for default behavior for templates (and uses) etc.

### ISSUE THREAD

**Issue by DipsoNOR** [RedReign/FoundryVTT-BetterRolls5e#197]
Recent updates have made quite a few things that I find handy simply not work, as I understand it to reduce the number of dialog boxes that show up.

However. In my case, I want to place templates for abilities like breath weapon for example.

Now I understand that people have different preferences about these things, which is why I'm suggesting that there should be an option in the settings of better rolls for what you want as default behavior for things like for instance a breath weapon...

**Comment by CarlosFdez** [comment]
the setting can't apply to breath weapons specifically though, it applies to item type. So "weapon" has default settings, "consumable" has default settings, "spell" has default settings, etc. That's why this is actually kinda tricky to handle.

I updated the defaults in the alpha version to also auto consume for consumables.

I can look into template default settings though.

**Comment by CarlosFdez** [comment]
Can you give me an example of what breath weapon you're talking about? I don't use breath weapons so need some examples to test with. Is it a weapon? A feat?

**Comment by CarlosFdez** [comment]
Final update but decided to release it, new feat default and all.

**Comment by DipsoNOR** [comment]
You know, I am an idiot to not give you an example of what i mean.

Monsters with non-spell abillities. Like fire-breath.
Example: any dragon. :D (I mean this _is_ dungeons and dragons :P )

**Comment by CarlosFdez** [comment]
Well, its not that I'm against options, its that options are often used as a cop out in situations where a good default would serve instead. Instead they should be last resort. That said a different alt attack default that has everything enabled might be a good way to handle it for certain cases.

The tweak I did seems to work for dragon breaths as well (they're features). I think its fine to default templates to on for everything. If an item has cone/circle range, most of the time you want templates to be on anyways.

**Comment by CarlosFdez** [comment]
Oh, just to be certain, you're aware that these settings are configurable on a per item basis correct (in the Better Rolls tab)? Double reading and you could configure it to use a template, just it had to be done per item.

**Comment by DipsoNOR** [comment]
Yes. 

The idea of doing this for every monster each time I imported from dndb, was not very tempting. :)

If i had to go through and set this up manually for everything. What ever seconds gained in game would be lost twofold, if not more in prep time. :P

Thankfully that is not the case. ;)

**Comment by CarlosFdez** [comment]
Gonna close this issue since I think the defaults should be fine as is for now. If this sort of thing is still a problem later on, feel free to open a new issue. There may be value in having alt rolls always consume resources no matter one, or an option spread.
