### ISSUE TITLE
[Bug] Consumables are not being consumed when set to "Consume Quantity" only

### ISSUE THREAD

**Issue by megahead11** [RedReign/FoundryVTT-BetterRolls5e#198]
It works fine with SRD items, like potions of healing; however, using homebrewed items is a different story. It seems if an item is set to consume quantity and no charges are set, the item is not consumed, regardless of other settings.

Here are the steps I used to reproduce this bug.

- Create a new consumable, name and all.
- Set activation cost to anything (I used "action")
- Ensure that the consumable has its limited uses set to 0/0 with nothing selected and has a quantity greater than 1 (quantity might not really matter)
-  Ensure "Destroy on Empty" is left unchecked. (Although checking it does not fix this bug)
- Check "Consume: Quantity"
- Quantity does not get used up regardless of how many times you click it. Tested on tidy5e and default sheets.

**Comment by CarlosFdez** [comment]
Verified it was indeed a problem. Can you try again on the latest version?

**Comment by megahead11** [comment]
Tested and it works again! Thanks :D Quick fix

**Comment by CarlosFdez** [comment]
Glad to hear! Thanks for reporting.
