### ISSUE TITLE
Levelled spells do not post to chat.

### ISSUE THREAD

**Issue by GvosRamsey** [RedReign/FoundryVTT-BetterRolls5e#20]
Cantrips work fine, as well as items (weapon attacks). Levelled spells (1-9) post nothing to chat.

**Comment by RedReign** [comment]
I can't reproduce this. Are there any errors in the console log you receive when rolling leveled spells?

**Comment by RedReign** [comment]
Cannot reproduce the error.

**Comment by IndigoGnat** [comment]
I am having this exact same issue.  If I change a level 1 spell to a cantrip, I am able to cast it.
