### ISSUE TITLE
Incorrect cantrip scaling for NPCs

### ISSUE THREAD

**Issue by archeresky** [RedReign/FoundryVTT-BetterRolls5e#200]
Currently, BetterRolls calculates the damage dice for cantrips cast by NPCs based on their CR. This is incorrect behavior. Monster Manual (p.10) states that for NPCs their spellcaster level is used for any cantrips they cast, that is also the core behavior for NPC cantrip damage dice. Below is an example of an Archmage (CR12, 18th lvl spellcaster) casting a firebolt and resulting rolls.

Vanilla roll (Refers to spellcasting level, dice is 4d10)
![image](https://user-images.githubusercontent.com/73297245/104963319-8f7cde80-59da-11eb-8f36-22ea2af151c6.png)

BR roll (Refers to CR, dice is 3d10)
![image](https://user-images.githubusercontent.com/73297245/104963042-fbab1280-59d9-11eb-908a-275f995624a6.png)

**Comment by CarlosFdez** [comment]
Interesting. Thanks for reporting it. Can't really do it at this time quite yet but once I find some free time I'll look into it.

**Comment by CarlosFdez** [comment]
Waited for my next d&d game to figure out if there were any additional bugs, and I did run into one which I added to this current release. Should be fine in the newest version. TY for reporting.

**Comment by archeresky** [comment]
Thanks for looking into it!
