### ISSUE TITLE
Problem with 1.3.x line initializing

### ISSUE THREAD

**Issue by mkemp** [RedReign/FoundryVTT-BetterRolls5e#204]
I'm running the following versions:

Foundry 0.7.9
5e System 1.2.4

When I install any version of BetterRolls for 5e in the 1.3.x line it seems that it fails to properly initialize. If I revert back to 1.2.2 BetterRolls for 5e works as expected.

I had first noticed this when I saw this error message from Token Action HUD (version 0.10.29).
```
Uncaught (in promise) ReferenceError: BetterRolls is not defined
    at RollHandlerBetterRolls5e.rollItemMacro (dnd5e-betterrolls5e.js:74)
    at RollHandlerBetterRolls5e._handleMacros (dnd5e-base.js:51)
    at RollHandlerBetterRolls5e.doHandleActionEvent (dnd5e-base.js:27)
    at RollHandlerBetterRolls5e.handleActionEvent (rollHandler.js:47)
    at handleClick (tokenactionhud.js:86)
    at HTMLDivElement.<anonymous> (tokenactionhud.js:93)
    at HTMLDivElement.dispatch (jquery.min.js:2)
    at HTMLDivElement.v.handle (jquery.min.js:2)
  ```
After digging a bit I realized that BetterRolls for 5e wasn't even showing up under module settings - even when disabling all other modules.

**Comment by CarlosFdez** [comment]
I don't know what to tell you, its functioning for me.

![image](https://user-images.githubusercontent.com/1286721/105937131-f0339900-6022-11eb-98ce-c87dc1091729.png)

Normally this happens if you haven't updated your 5e system or foundry, but it seems you have. If its not showing in the module list, it seems that Foundry is not detecting it.

**Comment by mkemp** [comment]
In the 'Manage Modules' screen I see 'Better Rolls for 5e' regardless of the version. Where I didn't see it get picked up by Foundry was in the 'Configure Settings' screen. This screen capture is when I have 1.2.2 installed. This entire section of configuration is missing once I install 1.3.x.

![module-settings](https://user-images.githubusercontent.com/33940/105946597-2d048d80-602d-11eb-9850-367209b911ef.png)

As far as narrowing this down... I've tried on Chrome (version 88) in both Windows 10 and Mac. These are the normal machines I access Foundry from. Neither show an error during the Foundry initialization. I checked the Network tab and the JS files for BetterRolls for 5e are loaded. While the files are loaded, it seems like the `Hooks` are not properly triggering. I also verified that there's no `BetterRolls` object available on the `window` object.

**Comment by CarlosFdez** [comment]
Someone actually just messaged me with this, saying that nothing would roll, but I joined their server and I rolled just fine, so this one does indeed seem to be a doozy. Maybe a race condition of some sort.

**Comment by mkemp** [comment]
The only other new-ish thing I've added to the setup was `libWrapper` as DAE and some other modules wanted it. That's been stable for over a month and doesn't cause problems with the 1.2.2 version.

**Comment by CarlosFdez** [comment]
I was in a voice chat with someone else with the same issue. It seems that on some people's computers, gsap will not import and that's causing the module not to work. I gave them a patched version where gsap is not used at all and then it worked. I'll have to look into making the import optional and investigating the root source of the problem.

**Comment by CarlosFdez** [comment]
@mkemp should work now, give it a shot. I changed the gsap import to relative. It seems to be a problem that can happen on instances of Foundry that are hosted on a server.

**Comment by Lethay** [comment]
Likewise for me: with 
Foundry 0.7.9
DnD5e 1.2.4
Better Rolls v 1.3.5

I get no settings and no rolls. Had to change Token Action HUD to go through the core roller because nothing was happening when it tried to go through Better Rolls.

Can't see anything in the console log with the filter "better".
![image](https://user-images.githubusercontent.com/5658454/106138963-b9fe3280-6164-11eb-87a2-7ecbb271d188.png)

**Comment by CarlosFdez** [comment]
@Lethay @mkemp Can you try again on 1.3.6? Tried an alternative way of importing gsap, and I made it so that even if the import fails the module keeps working.

Also, when you upgrade a roll (aka click crit upgrade or single roll mode and set to advantage/disadvantage) does the chat card border blink red? If so, its fully working, if not, its partially working.

**Comment by mkemp** [comment]
@CarlosFdez I'll give this a try this evening and let you know. Sorry, I had forgot to mention that this was hosted on a server.

**Comment by Lethay** [comment]
> 
> 
> @Lethay @mkemp Can you try again on 1.3.6? Tried an alternative way of importing gsap, and I made it so that even if the import fails the module keeps working.

That fixed it. I also had a look for gsap in the console log. Found a bunch of messages related to it,

```
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/ScrollToPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/gsap-core.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/CSSRulePlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/EaselPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/EasePack.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/CSSPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/Draggable.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/CustomEase.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/MotionPathPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/ScrollTrigger.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/TextPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/PixiPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/DrawSVGPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/PhysicsPropsPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/Physics2DPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/CustomWiggle.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/ScrambleTextPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/CustomBounce.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/GSDevTools.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/InertiaPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/MotionPathHelper.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/MorphSVGPlugin.js”. game:148:1
Loading failed for the module with source “https://my-server-url.com/scripts/greensock/esm/SplitText.js”. game:148:1
```
But it's utterly non-specific as to _why_ it failed to load. I had a quick look to make sure the URLs it's pinging are valid, and sure enough, they are. On my server they're at `/foundry/resources/app/public/scripts/greensock/` and are accessible on the browser by going to the URL that the module's trying to reach. Could you maybe catch the error to find out what's going wrong?

**Comment by Lethay** [comment]
Okay, I didn't know this is a built-in module and that makes life a lot harder. all.js gets called, but then it fails to load all of its own scripts at the same time? That baffles me.
I tried to wrap one of the import statements in a try/catch error, but whoops, you're not allowed to do that in javascript ("import statements must be at the top of a moduel").

Do you have any suggestions for debugging?

**Comment by mkemp** [comment]
Just updated to 1.3.6 and your change seems to have solved it for me. Thanks!

**Comment by CarlosFdez** [comment]
Unfortunately, I have no idea how I'd debug it. In fact I only guessed cause I saw a gsap import error at the top of someone's error log, and disabling let it work again (though with reduced vfx). Tried a relative import and failed, tried an import in module.json and it worked.

You can delay an import by using the import() function instead which returns a promise. But BetterRolls at least now doesn't import gsap, it just specifies it in the module.json and uses the global gsap attached to the window object. There may be other modules importing gsap causing those messages.
