### ISSUE TITLE
Alternative Critical Roll Method

### ISSUE THREAD

**Issue by DrWiFi** [RedReign/FoundryVTT-BetterRolls5e#208]
Hello,
Several youtube channels have recommended the following Critical Dice calculation that I would like to be able to use if it is possible.
Essentially the Base damage of the weapon is maxed, and critical dice is rolled on top of that. Features such as sneak attack do not get maximised. I do not think smite has to be considered since that is rolled and added after the attack.

Example: 

- Level 1 Rogue using Dagger with sneak attack: 1d4 + 4 +mod + 2d6
- Paladin with flametongue longsword: 1d8 + 8 +mod + 4d6 (can also be 2d6 + 12 if easier)
- Cleric using Level 1 Guiding Bolt: 4d6 + 24
- Half Orc with Greataxe: 1d12 + 12 + mod + 1d12 (savage attack)

Thanks

**Comment by CarlosFdez** [comment]
This is a Max Base and not Max Critical thing? I could consider it for a future release, but I'm currently busy with something and want to updates to fixes for now. That said if someone wants to add the calculation in, they're welcome to do so.

**Comment by DrWiFi** [comment]
Thanks, 
I think so, Max base before adding bonus dice from other features. 
I found a module which almost works called Max Crits (https://github.com/smilligan93/max-crit-foundry-dnd5e) which works well as long as you do not use any bonus dice added with Dynamic Active Effects for features such as sneak attack. (It just rolls them once without doubling) It also messes with the rolling a bit when it's active with another rolling module such as this one.
