### ISSUE TITLE
Delete Button Disappears After Re-Rolling And Subsequently 

### ISSUE THREAD

**Issue by jasparagus** [RedReign/FoundryVTT-BetterRolls5e#209]
Delete button missing after adding advantage and subsequently re-rolling the new (advantage) roll.
![image](https://user-images.githubusercontent.com/12389821/106216129-49b4d880-6187-11eb-9558-f135f948910f.png)

**To reproduce:**
1 - make a roll (e.g. a weapon attack)
2 - click "+" to "roll with advantage"
3 - click "reroll" on the upgraded roll
4 - a new card is spawned without a delete button

I've noticed this is intermittent, and am not 100% sure it isn't caused by interaction with another module. I'll keep playing with it and ideally update if I figure out what's going on.

Edit 1: the delete button seems to reappear after deleting previous messages, but not always.

**Comment by CarlosFdez** [comment]
I'm almost certain its from interaction with another module, but I'll keep it in mind during my next game and see if it happens there.

**Comment by jasparagus** [comment]
Looks like it was a conflict from another module on my end. Thanks for the heads up!
