### ISSUE TITLE
Apply Damage buttons do not appear on the Default Roll Damage bar

### ISSUE THREAD

**Issue by DandDPM** [RedReign/FoundryVTT-BetterRolls5e#21]
I love the module.  Thank you!  The only thing I have found is, as the title states, when you use the Default Roll functionality, the 4 buttons to apply damage do not appear.  It is only an issue because this module disables the right click to apply damage.  

Thanks!

![image](https://user-images.githubusercontent.com/65044691/81446881-9ebc4480-9149-11ea-9fcd-93ae971355e2.png)

**Comment by RedReign** [comment]
Unfortunately, I do not plan on adding the chat damage buttons to Default Rolls. However, I've re-added the right-click to apply damage in the next update. Thanks for the report, hope this helps!

**Comment by DandDPM** [comment]
Thank you! Thanks,Damien Pinto-Martin From: RedReignSent: Wednesday, May 20, 2020 4:36 PMTo: RedReign/FoundryVTT-BetterRolls5eCc: DandDPM; AuthorSubject: Re: [RedReign/FoundryVTT-BetterRolls5e] Apply Damage buttons do not appear on the Default Roll Damage bar (#21) Unfortunately, I do not plan on adding the chat damage buttons to Default Rolls. However, I've re-added the right-click to apply damage in the next update. Thanks for the report, hope this helps!—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
