### ISSUE TITLE
No fallback for scaling of cantrips cast by NPCs without spellcaster levels.

### ISSUE THREAD

**Issue by archeresky** [RedReign/FoundryVTT-BetterRolls5e#214]
This is partly connected to #200, after the fix, cantrip scaling for NPCs is correct when they have spellcaster levels but in case these are not defined (creature has Innate Spellcasting), there is no fallback calculation of the damage formula and it instead becomes the base damage.
According to Monster Manual, in this case monster CR is used:
"A monster with the innate ability to cast spells has the Innate Spellcasting special trait. Unless noted otherwise, an innate spell of 1st level or higher is always cast at its lowest possible level and can't be cast at a higher level. If a monster has a cantrip where its level matters and no level is given, use the monster's challenge rating."
This bug seems to also be present in core vanilla rolls.

**Comment by CarlosFdez** [comment]
Seems to be the case. If it gets resolved in the vanilla system, let me know and I'll adjust BR to match that. There's a chance they're going to improve the spell scaling methods and it'll have to adjust to that anyways.

**Comment by CarlosFdez** [comment]
Implemented it anyways actually. I also saw that you reported it on the 5e repository.

**Comment by CarlosFdez** [comment]
Gonna assume its been working, let me know if it isn't though.
