### ISSUE TITLE
healing icon path is broken in certain foundry installations

### ISSUE THREAD

**Issue by itamarcu** [RedReign/FoundryVTT-BetterRolls5e#215]
as part of [this commit](https://github.com/RedReign/FoundryVTT-BetterRolls5e/commit/13a51384cbc69a11b8c76a4b03a0c9538b583745?short_path=c545a11), the heart-plus SVG is loaded through a url that assumes foundry runs without a subdomain in the address.

the bug causes the healing icon to not be rendered (showing up as an empty white box when hovering over a message).

the code:

```css
	background-image: url("/modules/betterrolls5e/css/heart-plus.svg");
```

causes this error in my server:

`GET https://my.server.address/modules/betterrolls5e/css/heart-plus.svg 404`

this is similar to a bug that happened with the DND5e system - [see here for a very similar problem and solution](https://gitlab.com/foundrynet/dnd5e/-/merge_requests/139).

I tried solving this myself locally, and I believe the solution is to change the above line to:

```css
	background-image: url("../../../modules/betterrolls5e/css/heart-plus.svg");
```

it works in my installation, at least, so I suggest you try it in yours too and make the change assuming it indeed still works for you.

**Comment by itamarcu** [comment]
oh, and there's actually one more instance of a URL like this that is broken (just less noticeable):

```css
	background-image: url(/icons/svg/d20-grey.svg);
```

can be fixed with:

```css
	background-image: url(../../../icons/svg/d20-grey.svg);
```

**Comment by CarlosFdez** [comment]
I'll give it a shot once I find time, thanks for reporting.

**Comment by CarlosFdez** [comment]
seems to work for me

**Comment by itamarcu** [comment]
it consistently breaks for me in a server where the addresses are `https://server.address/subdomain1`, `https://server.address/subdomain2`, etc (we have multiple installations with multiple licenses).

**Comment by CarlosFdez** [comment]
@itamarcu I meant that I did your fix, and it works for me. Sorry for not clarifying. Should be available if you update.

**Comment by itamarcu** [comment]
ah, okay, that's awesome!  thanks a lot :]
