### ISSUE TITLE
trowable weapons roll damage 2 times

### ISSUE THREAD

**Issue by draczer01** [RedReign/FoundryVTT-BetterRolls5e#216]
hi, I love the module, but when I attack with a javalin the javalin rolls damage 2 times, this is anoying specially if you automate damage

**Comment by CarlosFdez** [comment]
Before I begin to address this, can you show me how the Javelin is configured with a screenshot? Also just to be certain, you're on the newest version?

**Comment by draczer01** [comment]
I have posted the config here: 
https://imgur.com/gallery/NIc95Ux

and to make it clear this is the module responsable I have disabled everithing but this module and the bug persists, its just when I disable this module that this happens

**Comment by draczer01** [comment]
this only happens when an item is consumed

**Comment by CarlosFdez** [comment]
That's more than enough help, I was able to reproduce it. Its because longbows need to add arrow damage to the roll, but I forgot to account for items that consume themselves.

**Comment by CarlosFdez** [comment]
Its been fixed, but open a new issue if there's still a problem.
