### ISSUE TITLE
Showing disadvantage/advantage query for spells requiring a saving throw

### ISSUE THREAD

**Issue by archeresky** [RedReign/FoundryVTT-BetterRolls5e#217]
The option to show a query window for disadvantage/advantage appears also when rolling Saving Throw based Spells. Although this  might not necessarily be a bug in itself, having this window appear for this kind of a roll is kind of redundant.

**Comment by CarlosFdez** [comment]
I would recommend not using that advantage/disadvantage query. The way it works is an awkward workflow and its hard to fix. I think Red was going to fix it before he became indisposed, but I'm tempted on removing it.

Would using single rolls and using the hotkeys or editing the roll by clicking the +/- mouseover buttons be a better workflow?

**Comment by archeresky** [comment]
> Would using single rolls and using the hotkeys or editing the roll by clicking the +/- mouseover buttons be a better workflow? That already exists and I figured it was better. Have you tried that out?
I haven't considered that workflow, but I guess it works instead. If the query window is marked for deletion, I guess it's time to say goodbye to it.

**Comment by CarlosFdez** [comment]
So despite closing it, I have been told a good reason for maintaining it, and that's that it curbs certain types of undesirable behavior. So fixing it for next version, and adding it as a new option to the dropdown list for num rolls (so triple threat, dual rolls, single roll, and query will be the options). It will break old configs but simplify project setup a tad short term.
