### ISSUE TITLE
Better Rolls and Magic Items together cause uncaught TypeError

### ISSUE THREAD

**Issue by KPhoenix** [RedReign/FoundryVTT-BetterRolls5e#220]
I understand that Better Rolls doesn't actively advertise compatibility with Magic Items at this time, but I thought I might as well bring this up just in case it is a BR issue and you're up for implementing a fix. If not, no big deal.

* Foundry 0.7.9
* D&D 5e system 1.2.4
* Better Rolls 1.3.7+
* Magic Items 2.0.8

Tested in a clean world with only BR and MI enabled.

Starting with BR 1.3.7, spells gained via a magic item with Magic Items settings cause strange behavior. At different points in time while using MI and BR together, I've noticed the following error in the Chrome dev console:

Uncaught (in promise) TypeError: Cannot read property 'data' of null
    at addButtonsToItemLi (betterrolls5e.js:167)
    at addItemSheetButtons (betterrolls5e.js:141)
    at hooks.js:37

So far, I've seen this when:

* With BR and MI enabled, add a magic item from the Magic Items compendium (e.g., Wand of Fireballs) to a character sheet. The error is logged as soon as the item is added.
* With a Magic Item added to a character sheet, log into the test world, open that character sheet, and attempt to cast the MI-granted spell (e.g., Fireball) on that sheet. The first attempt will work correctly but log the error to the console. Subsequent attempts to cast are unresponsive and log "level > 0" to the console. (Rolling something else on the sheet "fixes" the MI spell, but then casting it a second time logs the error and becomes unresponsive again.)
* With a Magic Item added to a character sheet, log into the test world and open that character sheet. The error appears in the console immediately upon opening the sheet. Any attempts to cast the MI-granted spell log no further errors, but do post empty messages to the Foundry game chat.

I don't yet know what causes which of the latter two cases to happen when, unfortunately. At the moment it just seems random each time I open my test world.

With the caveat that I'm not an expert, some poking around the diffs tells me this commit 9f9e0a5c3264aae672a5d1b644454e801a4526af introduced the conflict.

Someone has already [reported this](https://gitlab.com/riccisi/foundryvtt-magic-items/-/issues/72) to Magic Items' dev as well, so if the problem is on MI's end, feel free to disregard and close.

Thanks!

**Comment by CarlosFdez** [comment]
Sorry for the late reply, was really busy these past few days but I have some time again. I'll start looking into it. Thanks for reporting it!

**Comment by CarlosFdez** [comment]
Should work now, though Magic Items doesn't use better rolls. That's something that'd need to be on their end, but I do plan on eventually patching the core roller in a future release.

**Comment by KPhoenix** [comment]
Yep, that fixes it! Yeah, I realize MI isn't integrated yet; just wanted to be sure they could at least play nicely together, and now they do. Thanks for looking into this!

**Comment by CarlosFdez** [comment]
No problem. Unfortunately any easy integration has to come from them, but I do plan on eventually "replacing" the core roller rather than adding on tap, so that as far as MI is concerned, BR is the core roller. This will likely break a lot of module compatibility, so it will occur during the new foundry alpha series (since everything is breaking anyways!)

That said, I hope this tides you over in the short term. Good luck with your games!
