### ISSUE TITLE
Ranges feature only looks at max range.

### ISSUE THREAD

**Issue by TheBalzan** [RedReign/FoundryVTT-BetterRolls5e#227]
If a feature or item has a range but no max range the range feature will think there is no range set.
Ie a cantrip with 120 range which by default is set as 120/0 will say that the target is outside the range for the cantrip, as the feature is looking only at the max range.

**Comment by CarlosFdez** [comment]
There is no range detection feature in Better Rolls. Are you talking about the footer?

**Comment by TheBalzan** [comment]
Oops I'm thinking of midi QoL.
