### ISSUE TITLE
Setting an item to consume "Quantity" doesn't work if the item has uses.

### ISSUE THREAD

**Issue by cs96and** [RedReign/FoundryVTT-BetterRolls5e#228]
If you have an item that has has any amount of uses (charges, number per long rest etc), then setting Better Rolls to consume "Quantity" instead of "Uses" does not work.  No uses or quantity are used up when rolling the item.

**Comment by CarlosFdez** [comment]
Should be handled in the newest version, lmk if it works!

**Comment by cs96and** [comment]
Thanks!
