### ISSUE TITLE
At-will and innate spells with unlimited uses show a dialog box with only one button

### ISSUE THREAD

**Issue by cs96and** [RedReign/FoundryVTT-BetterRolls5e#229]
If I set a levelled spell to "At-will" or "Innate" with unlimited uses, then when clicking to roll the spell, a dialog box is shown, with only one button.

Given that there is nothing to be asked, the dialog should not be shown and the spell rolled immediately after clicking/

![image](https://user-images.githubusercontent.com/898086/109730585-a144ca80-7bb1-11eb-8a2e-6dd81356fee0.png)

![image](https://user-images.githubusercontent.com/898086/109730713-d81ae080-7bb1-11eb-8a82-337fff9f97a4.png)

**Comment by CarlosFdez** [comment]
Should be fine now!

**Comment by cs96and** [comment]
Thanks!
