### ISSUE TITLE
Feature request: make BetterRolls5e compatible with FVTT 0.5.6 reveal roll messages

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#23]
Hello,
Introduced in FVTT 0.5.6 the GM can now reveal his rolls when they are private, hidden or "blind".
This feature appears not to be working with BetterRolls5e activated.
Not only it doesn't work on BetterRolls5e Rolls but also on regular rolls like : "/r 1d6"

**Comment by RedReign** [comment]
Fixed in the next update! Thanks for the report.
