### ISSUE TITLE
Suggestion: BetterRolls functions should return a Promise

### ISSUE THREAD

**Issue by cs96and** [RedReign/FoundryVTT-BetterRolls5e#230]
It seems that the BetterRolls quickRoll functions (e.g. `quickRoll`, `quickRollById`, `quickRollByName` etc) always return `undefined`.  This makes them difficult to use in macros.  E.g. if you want to cast a spell from a macro using BetterRolls, then there is no way to know if the user actually cast the spell or closed the dialog box without casting it.

Foundry's `game.dnd5e.rollItemMacro` will return a Promise when called.  The result of the Promise will be undefined if the user cancelled the item roll (e.g. by closing the dialog), or will contain a ChatMessage object if the spell was actually cast.

It would be useful if Better Rolls also returned a Promise so that they are more useful in macros.

**Comment by CarlosFdez** [comment]
I normally use newItemRoll(), but I did forget about those yeah. They should definitely return Promise<CustomItemRoll>.

**Comment by CarlosFdez** [comment]
Update to the newest version and its done, though it returns Promise<ChatMessage> instead to maintain consistency with Foundry instead.
