### ISSUE TITLE
Better Rolls for 5e installed but does appear in Manage Modules

### ISSUE THREAD

**Issue by algenonchigley** [RedReign/FoundryVTT-BetterRolls5e#233]
I have installed Better Rolls for 5e from the Foundry Setup. However, the module does not appear in the list of modules in Module Management. I have two other modules installed - Actually Private Rolls and Tidy UI - Game Settings. I'm using Foundry VTT version 0.7.9 with DnD5e 1.2.0. Foundry is running on Amazon Linux.

**Comment by Stendarpaval** [comment]
Did you try updating your dnd5e system? Its latest release is 1.2.4, and you mentioned that you’re on 1.2.0.

**Comment by algenonchigley** [comment]
That did the trick! Many thanks.
