### ISSUE TITLE
Spells with mode "Innate Spellcasting" do not place templates

### ISSUE THREAD

**Issue by tosh823** [RedReign/FoundryVTT-BetterRolls5e#236]
Hi!
Noticed the issue with innate spells. When using Better Rolls for such items (tried with Darkness spell), the chat card is simply put in the chat, no dialog to place template is shown, nor the button in the chat card exists.
![Darkness](https://user-images.githubusercontent.com/11402260/110527322-7dd4cf00-811f-11eb-86c1-cb47f7debc3e.PNG)

**Comment by CarlosFdez** [comment]
Should work now, let me know.
