### ISSUE TITLE
Compatibility issue with Token Action HUD

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#241]
Available at https://github.com/espositos/fvtt-tokenactionhud/issues/191 - it is extremely popular QoL mod for accessing rolls and attacks without the character sheet.

When Better Rolls for 5E is turned on, TokemActionHUD attacks will not trigger anything.

**Comment by CarlosFdez** [comment]
Interesting, because I made Better Rolls work via default rolls. Try it in non better rolls mode.

I should probably still look into it, but it should work like that in the meantime?

**Comment by apoapostolov** [comment]
Hello, I can confirm it is only the weapons in the Inventory tab of TokenHUD, rolls of spells (such as Eldritch Blast) that has attack and benefits from betterer, roll properly. 

![image](https://user-images.githubusercontent.com/4083812/111886547-16e4cf00-89d7-11eb-9009-29d44794af4f.png)

**Comment by CarlosFdez** [comment]
So it works in better rolls mode (in the token action hud settings), but it actually does not work in core mode. Figured out the root cause and I'm pushing a fix.

**Comment by apoapostolov** [comment]
I can confirm this is now fixed.
