### ISSUE TITLE
Buttons in item cards appear twice in Tidy5E

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#242]
![image](https://user-images.githubusercontent.com/4083812/111886737-b2c30a80-89d8-11eb-8719-354def27fd5f.png)

**Comment by CarlosFdez** [comment]
Not sure how you're doing this. Try updating everything again, and if its still happening, share your module list?

![image](https://user-images.githubusercontent.com/1286721/111929377-8f599780-8a8c-11eb-9c5b-cda35b751bb6.png)
Its fine for me.

**Comment by apoapostolov** [comment]
Closing, until I reconfirm it as the doubling disappeared.
