### ISSUE TITLE
Incompatibility with Automated Animations from JB2A animation project

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#244]
The mod Automated J2BA Animations is a way to automatically assign animations from the massively popular JB2A collection of animated effects to weapons in 5E, PF1, soon others. Link at: https://github.com/otigon/automated-jb2a-animations

When Better Roll for 5E is turned on, only a subset of weapons show animations - those that have animations assigned to them via name recognition - but the more customizable way of assigning animations via keywords stored in the source field do not work. 

I think this is because the source field, whether shown or not, is not passed by Better Rolls. Please check the compatibility between the mods and ensure that they can work together

Here's how to replicate the issue:
1. Take an uncommon 5E weapon such as a sickle that is guaranteed not to be recognized by name. Uncommon weapons are all not mentioned here: https://github.com/otigon/automated-jb2a-animations/blob/main/PDF/Keywords.md
2. Put a keyword in the source field such as 'sword' as described here: https://github.com/otigon/automated-jb2a-animations/blob/main/PDF/Keywords%20and%20Colors.pdf (I suggest sword as it is available in the free JB2A pack, no need to pay to access the full one)
3. Activate Automated Animations and JB2A Free mods.
4. Target your enemy while selecting your actor.
5. Run a Better Rolls attack and you will see no animation

Then you can do the same with a Sword and do an attack and since it is recognized via name it will play the animation... it is just those that rely on the source field do not play animations.

**Comment by CarlosFdez** [comment]
I think I fixed it, but I can't really test it completely as I don't know where source is. I don't see it in weapon details. Once I've confirmed it works I'll push it up as a new release.
