### ISSUE TITLE
"Magical" items don't automatically roll attacks

### ISSUE THREAD

**Issue by itamarcu** [RedReign/FoundryVTT-BetterRolls5e#245]
If you set an item's "Magical" property to true, and then quick-roll it, it will show the default foundry "Attack" and "Roll" buttons.

**Comment by CarlosFdez** [comment]
@itamarcu need some more info. Are you running it with midi? Magic Items module (you said magical property which is different)? Is this version 1.4.4? If none of these, can you try disabling modules to see if its from a module incompatibility?

I added the magical trait to Frost Brand Longsword and its still working.

**Comment by itamarcu** [comment]
Right, sorry.  I'm running with a lot of modules including Magic Items, on BetterRolls 1.3.9.

I will update the module, try disabling other modules, and let you know if it works or how to reproduce it if the bug still happens.

**Comment by itamarcu** [comment]
Looks like everything works now.  Sorry for the false alarm!
