### ISSUE TITLE
[Suggestion] Apply Temporary HP?

### ISSUE THREAD

**Issue by MarceloCortezz** [RedReign/FoundryVTT-BetterRolls5e#247]
When using the Full Heal target button with a Healing (Temporary) value, it heals the target instead of giving Temporary HP (video).

Is it possible to give Temp HP when your spell uses Healing (Temporary)?
Example: False life spell gives 1d4+4 temp hp.

https://user-images.githubusercontent.com/79060716/112327178-f72dff00-8c93-11eb-87f1-a45e68392f1f.mp4

**Comment by CarlosFdez** [comment]
Will be superceding core on this (they don't have apply temp hp) but it is something that's sorely needed so I'll add it to my personal todo list.

**Comment by CarlosFdez** [comment]
And it should be implemented, update and let me know how it goes.

**Comment by MarceloCortezz** [comment]
It worked perfectly! And even asking to replace actual temp HP with the new value! Amazing!
Thank you for the quick response!

**Comment by CarlosFdez** [comment]
No problem! Its definitely something I was putting off till 5e core supported it, but with 0.8 incoming they wouldn't have time for new features like that so I just did it here. Glad its working out for you.

Closing the issue, good luck with your games.
