### ISSUE TITLE
Feature request: compatibility with new resource consumption (0.9)

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#25]
Hi,

5e system has a new resource consumption mechanism:

> Items can now define a consumed resource which is used when the item card is played or when an attack roll is made (in the case of ammunition). Consumed resources can be ammunition, materials, a character attribute, or the number of uses/charges allowed by another owned item. The relevant resource is automatically deducted when the item is used. This works great for tracking resource spenders that reference a common resource pool (like Sorcerer metamagic, Bardic Inspiration uses, Monk Ki points, or Fighter superiority dice). This also allows for ammo tracking with weapons which require physical ammunition, or strict tracking of spell components.

BetterRolls5e prevents to use it right now.

**Comment by RedReign** [comment]
Currently waiting for dnd5e system to update. Right now it doesn't support item quantity consumption. When it does so, I'll work on adding proper Consumables support

**Comment by kpad-git** [comment]
Just FYI, I am using Foundry 0.6.0 and 5e system 0.92. I tried disabling better rolls and resource consumption is working. But if I enable better rolls (version 1.0.8), it doesn't work. So it looks like the system has whatever is needed now (the issue mentioned above by RedReign is marked closed too).

**Comment by DarKDinDoN** [comment]
Yep, not sure what is needed for BetterRolls, but seems D&D 0.92 is working fine with quantity consumption.

**Comment by RedReign** [comment]
My issue was that a consumable with 1 quantity left and no "charges" data does not actually reduce its quantity.

However, I've implemented a fix for better rolls logic to work with consumption, but it's slightly different than how base dnd5e handles it, to support the use cases that currently aren't supported. It will be implemented in the upcoming version 1.1.0.

**Comment by DarKDinDoN** [comment]
Great. Thx @RedReign
