### ISSUE TITLE
Option to automatically applay DAE 

### ISSUE THREAD

**Issue by spirritus** [RedReign/FoundryVTT-BetterRolls5e#250]
Hi there,

currently there is an option to enable a DAE button.
Another option to automatially apply said DAE effects would be awesome.
If I recall correctly that was the default in the past.

Cheers

**Comment by CarlosFdez** [comment]
That was actually never the default, that was a feature in midi qol. Better Rolls had no concept of active effects or applying them until recently.

If you're using midi to apply effects and don't want the button to show, then enable it in midi and disable it in better rolls and it should work.
