### ISSUE TITLE
Please extend + and - adv/disadv buttons for skill checks and saving throws

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#254]
The functionality is great but unfortunately only limited to attack rolls. My players are very used to these buttons being available post roll when the DM allows advantage or forgets to claim disadvantage, so they can be used on the fly.

**Comment by CarlosFdez** [comment]
But it does work for checks and attack rolls. Unless of course they're holding shift. Are you using it in combination with midi?

**Comment by CarlosFdez** [comment]
Gonna close this since I assume its been resolved.
