### ISSUE TITLE
Disable the "Enable Chat Damage Buttons" for players?

### ISSUE THREAD

**Issue by thejoester** [RedReign/FoundryVTT-BetterRolls5e#256]
So I noticed that if the "Enable Chat Damage Buttons" is enabled my players can see the buttons, but when they click on them it will only damage themselves (because they do not own the NPCs - why would they?) so its confusing to them. Even if it would work I would prefer to not let my players handle damaging NPCs. Is there a way to let ME as DM use these buttons because they are VERY useful, but not show them to the players?

**Comment by CarlosFdez** [comment]
Honestly, this is a pretty good idea, I might do this once I find some time.

**Comment by CarlosFdez** [comment]
Should be implemented now, let me know how it works.

**Comment by thejoester** [comment]
I get a popup that just has a "Yes" and "No" but no change in behavior, the player still damages its own token, not the target token and I see no options to hide these buttons from the player. 

![image](https://user-images.githubusercontent.com/7744795/116516481-e2dcb380-a88a-11eb-8262-8600a426f850.png)

**Comment by CarlosFdez** [comment]
Its an option that was added, make sure to enable it.

Also for whatever reason that dialog is untranslated now, that's supposed to be "Show Crit Damage?"

**Comment by thejoester** [comment]
Okay, I think I may not have gotten the full update or something previously. I removed the module and reinstalled it and now in the options I see the "DM Only" option and tested it and it seems to work! 

Thanks so much!

**Comment by CarlosFdez** [comment]
No problem! And I also just fixed the regression involving the apply crit label. Sorry about that.

Good luck with your games.
