### ISSUE TITLE
Dice sound not playing on cantrips and certain abilities

### ISSUE THREAD

**Issue by JackrabbitSlim68** [RedReign/FoundryVTT-BetterRolls5e#257]
Since the latest update the dice roll sound is very hit and miss. Our cleric gets sound with sacred flame but not spare the dying,guidance or thaumaturgy. Also our monk when using ki actions. no dice sound emits.

**Comment by CarlosFdez** [comment]
This was resolved in a DM, but rolls without dice don't make roll sounds, so closing the issue.
