### ISSUE TITLE
Compatibility issue with Token Action HUD

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#258]
Skills and Saves rolled from Token Action HUD do not get better controls (adv/dis and reroll). 

I also raised this at https://github.com/espositos/fvtt-tokenactionhud/issues/211

**Comment by CarlosFdez** [comment]
Make sure to set the roller in the options for Token Action Hud to Better Rolls. Better Rolls does not override the actor functions. It probably should though.

**Comment by apoapostolov** [comment]
OK, let me check and get back to you.

**Comment by apoapostolov** [comment]
Yes, this was the fix. I have used TAHUD set so long, I forgot it had so many options.
