### ISSUE TITLE
Bug: Proficiency bonus not added to skill checks

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#26]
Rolling a skill from the sheet doesn't apply the proficiency bonus to the roll.

Example:
Monk lvl 1 with the "monk class" item set to 1.
Adding the proficiency bonus to a skill by checking it (tick on the left)
Rolling any skill results in 1d20 being rolled without the Proficiency

**Comment by DarKDinDoN** [comment]
I believe the hotfix is on line 167 of custom-roll.js.
Replace:
```javascript
let parts = ["@mod"],
    data = {mod: skill.mod},
    flavor = null;
```
with:
```javascript
let parts = ["@mod", "@prof"],
    data = {
        mod: skill.mod,
        prof: skill.prof
    },
    flavor = null;
```

**Comment by RedReign** [comment]
Fixed in the next update! Thanks for the report!
