### ISSUE TITLE
Ammunition shouldn't get bonuses from Actor Global Bonuses

### ISSUE THREAD

**Issue by RufusTiki** [RedReign/FoundryVTT-BetterRolls5e#261]
So I noticed with a Sharpshooter macro that was using an Active Effect of "data.bonuses.rwak.damage" and "data.bonuses.rwak.attack" that at least the damage modification was showing up twice when I was using consumable ammo that had a bonus, i.e. Arrows +3. It applied the +10 damage both on the Bow Damage as well as the Arrow Damage.

I believe this can be fixed my changing line 250 of fields.js to the following:
				if (isFirst && rollData.bonuses && item.data.type != "consumable") {

Maybe it's better to filter out item.data.data.consumableType!="ammo" instead? Dunno. :D

Hope that helps. Seems to work for me!

**Comment by CarlosFdez** [comment]
Can confirm this is indeed the case. Sorry I didn't see this until now.
