### ISSUE TITLE
Is 1.4.11 supposed to require foundry 0.8.3?

### ISSUE THREAD

**Issue by RufusTiki** [RedReign/FoundryVTT-BetterRolls5e#268]
I downloaded 1.4.11 on my personal install of 0.7.9 (to get the ammo fix) but a few days later when trying to update my group's install it's saying 0.8.3 is required. 
Thanks.

**Comment by CarlosFdez** [comment]
It does not, thanks for the report. I had started the port but I forgot that unlike my other project the module.json comes from the master branch, and not from the releases.

Should be fixed now.

**Comment by RufusTiki** [comment]
Great. It worked! Thanks.
