### ISSUE TITLE
Feature request: Have the auto damage/heal buttons account for adjustments to max HP

### ISSUE THREAD

**Issue by zacdemon** [RedReign/FoundryVTT-BetterRolls5e#27]
Right now the auto damage/heal buttons do not respect adjustments to max HP made on the character sheet. Would be nice for situations where a characters max HP was modified so that they don't over/under heal themselves.

**Comment by RedReign** [comment]
I use the default damage application functions in dnd5e, so this is better suited as a core system feature requests for damage application.
