### ISSUE TITLE
Suggestion: tokenid passed in chatmessage flags.betterrolls5e should be the token uuid

### ISSUE THREAD

**Issue by tposney** [RedReign/FoundryVTT-BetterRolls5e#273]
The tokenId passed is of the form:
```
    "xMH6dt9g5Wt35rd3.j0qYEXalnqLzbbzH"  
```
There is a uuid defind for tokens which looks like
```
     "Scene.xMH6dt9g5Wt35rd3.Token.j0qYEXalnqLzbbzH" 
 ```
which foundry knows about and can easily recover the token.

I'd suggest passing token.uuid instead of the constructed id.

**Comment by CarlosFdez** [comment]
Is this new for 0.8? I should definitely look into it. 5e has generally used the former and I wanted to be consistent with it, but it is pretty ugly relying on it.

**Comment by CarlosFdez** [comment]
Anyways, its implemented in the newest release. I'll keep on eye for if items/actors do the same thing in 5e.
