### ISSUE TITLE
Hotbar : "No item is known with that ID on actor"

### ISSUE THREAD

**Issue by Cheezegami** [RedReign/FoundryVTT-BetterRolls5e#275]
When trying to put spells on the hotbar it gives a "No item is known with that ID on actor"

When dragging the spell from the hotbar it defaults to "BetterRolls.quickRollById("Hv4Lx7FaBh2oTkyd", "undefined"); the undefined part is interesting, since that probably means the actor is assigned, but it doesn't receive the item ID properly.

This is the case both as a DM and as a player.

This problem persists if the only modules I have enabled are BetterRolls and libWrapper.

I've tried different character sheets, but they all seem to give the same issues on a drag.

![chrome - 28-05-2021_11;09;45 ](https://user-images.githubusercontent.com/23402028/119964416-7cda6d80-bfa9-11eb-845b-e976699c5988.png)

**Comment by CarlosFdez** [comment]
Can confirm this is the case. Thanks for reporting! Gonna look to fix this, and I might as well make the macros more cross-module compatible while I'm at it.

**Comment by CarlosFdez** [comment]
Should be fixed and also compatible with core 5e (aka the macros should still work even if better rolls is disabled).
