### ISSUE TITLE
Spell slot not being consumed when rolled with better rolls.

### ISSUE THREAD

**Issue by SamuelStork** [RedReign/FoundryVTT-BetterRolls5e#278]
Steps to reproduce:
1. Clean install world + better rolls 5e + libWrapper
2. Create actor and add spell of 1st level or higher and 1 or more spell slots of that level. 
3. Quickroll spell
4. Click on Cast Spell with consume spell slot checked
5. Spell will cast but slot will not be consumed. 

I have tested it with all spell levels. Augmenting a spell does not decrease the number of spell slots either. 
Kind regards, Samuel Stork

**Comment by CarlosFdez** [comment]
Should be fixed now, alongside some other minor bugs that I caught while trying to fix it.

**Comment by CarlosFdez** [comment]
Seems like it works, so I'm not closing. Thanks for reporting!
