### ISSUE TITLE
Blind rolls not working

### ISSUE THREAD

**Issue by Tapperton** [RedReign/FoundryVTT-BetterRolls5e#279]
![image](https://user-images.githubusercontent.com/85312950/120698177-f34a0480-c4ae-11eb-9b31-ab8eda20abfd.png)
Blind GM rolls don't seem to hide properly when rolled as skill checks. Rolling regular dice seems to work, but not posting the rolls directly from the character sheet.

**Comment by CarlosFdez** [comment]
Can you give some more information on how this is happening? Are you viewing as the player or viewing as the GM? Rolling as the player or rolling as the GM? The background is purple which is the correct color for blind GM rolls. What was the first roll you're having?

Also test without plutonium. :^)

**Comment by crash1115** [comment]
Rolling as a player: Private GM Rolls, Self Rolls, Blind rolls are all visible to me, all other players, and the GM. The card styling is right (the muted purple and blue where appropriate) and the "Name privately rolled some dice" appears at the top of the cards as expected.

Rolling as a GM: Same behavior.

![image](https://user-images.githubusercontent.com/41387713/120846472-2ab4c180-c540-11eb-914f-73ee0dab0192.png) The other mod is active libwarapper.

**Comment by CarlosFdez** [comment]
Seems its a Foundry issue:
https://gitlab.com/foundrynet/foundryvtt/-/issues/5302

Going to see how its resolved, but if they don't resolve it we'll have to do some hackery and the thought scares me.

**Comment by jrmiller82** [comment]
And unfortunately looks like not considered a bug by them. Ugggh. That's a crazy regression, that they've tagged for next stable, as opposed to a bug fix.

**Comment by jrmiller82** [comment]
> 
> 
> Seems its a Foundry issue:
> https://gitlab.com/foundrynet/foundryvtt/-/issues/5302
> 
> Going to see how its resolved, but if they don't resolve it we'll have to do some hackery and the thought scares me.

Looks like Atropos wants module developers to create custom roll types to render custom content. Seems like cutting off your foot to fit in a small shoe.

**Comment by ComedianTF2** [comment]
Looks like the 0.8.7 update fixes this issue, where it no longer shows the results

_Dice System_
_Whispered rolls have been returned to the workflow of always displaying that they were "rolled privately" for any User that does not have permission to view the content of the roll-type Chat Message._

![image](https://user-images.githubusercontent.com/33683622/122093221-c11b9980-ce02-11eb-8e51-2b552099123a.png)

**Comment by CarlosFdez** [comment]
Yup! Confirmed it was the case as well. Thank you for the reminder.
