### ISSUE TITLE
In 0.8.6, charges are not consumed.

### ISSUE THREAD

**Issue by huxoll** [RedReign/FoundryVTT-BetterRolls5e#280]
With Better Rolls enabled, using e.g. a breath weapon doesn't consume the charge.  The card is printed to chat with attack and damage, but the ability still shows as charged on the sheet.

It really freaked out my players when I clicked it a few times in a row trying to get it discharged.

I believe it's related to Better Rolls, with the module turned off the ability goes to not charged after use as usual.

FoundryVTT: 0.8.6
BetterRolls: 1.5.2

**Comment by CarlosFdez** [comment]
Action Charge looks like a new mechanic in the 5e system. The defaults should probably work for action charge but they currently do not, but interestingly enough seems that Better Rolls does handle it if you edit the item and enable action charge to be consumed.

I don't recall ever implementing Action Charge, so this is very interesting. 

I'm going to look into changing the default for action charge somehow, but for all existing actors you'll have to edit the item's better rolls property to consume the charge even once I do change the default.

**Comment by CarlosFdez** [comment]
New version pushed, any newly created or important actor/item will now consume any available actions by default. Old actors need their features edited to enable action recharge consumption in the better rolls tab.

![image](https://user-images.githubusercontent.com/1286721/120974150-c95a4180-c73d-11eb-9925-5d88997d90d9.png)
