### ISSUE TITLE
Request: Compatibility with "Hide GM Rolls" Module

### ISSUE THREAD

**Issue by MathewBissonnette** [RedReign/FoundryVTT-BetterRolls5e#282]
Hide GM Rolls has a setting that hides the description on cards posted by the DM, displaying only the title. See attached screenshots for behavior with and without BetterRolls5E enabled. Both of the screenshots are from the player view. The DM still sees the description on the card in the chat.

With BetterRolls
![With BetterRolls](https://user-images.githubusercontent.com/24984298/121455472-5e855200-c959-11eb-963c-8c6105b7fd5f.png)

Without BetterRolls
![Without BetterRolls](https://user-images.githubusercontent.com/24984298/121455475-5fb67f00-c959-11eb-9a94-9529644d7bdc.png)

DM's Screen
![DM View](https://user-images.githubusercontent.com/24984298/121455651-b0c67300-c959-11eb-995f-fc22797038c4.png)

**Comment by CarlosFdez** [comment]
What does this module offer that private rolls don't? Given that Hide GM rolls alters existing HTML, I think it has to support better rolls and not the other way around (since its based on a selector path). If there's something easy I can do for them (like change the class name of a tag) I can do that but otherwise this is not possible.

Private/Blind rolls are currently not working because of a Foundry bug, they'll start working in Foundry 0.8.7.

**Comment by MathewBissonnette** [comment]
It's basically a compromise between rolling in front of the screen and rolling behind it. With Private/Blind rolls the players don't see the results. With public rolls they see the results and all of the modifiers that went into it. With Hide GM Rolls, the total result is displayed but the modifiers aren't. That way the players don't get any meta knowledge about the creature's stats but can still enjoy knowing that no dice are being fudged.

If the problem is on their end I'll try dropping a ticket on that repo. Thanks for the help!

**Comment by sPOiDar** [comment]
Feel free to close here, I'll add an alternative selector for BetterRolls.

**Comment by CarlosFdez** [comment]
Sure! Thanks for offering. I see what the intent is now with the module. Not a bad idea.

**Comment by sPOiDar** [comment]
BTW @CarlosFdez you should create an empty container when hiding item descriptions rather than omitting the div entirely, otherwise Foundry will throw errors if users click the item heading. I can open another issue if you like, though I don't use the module personally.

**Comment by CarlosFdez** [comment]
I had seen that yeah, but it seemed like vanilla 5e had the same problem. If they resolved it though I'll give it a shot at some point (probably by adding a blank description field in the preset even if description is disabled in the configuration).
