### ISSUE TITLE
BetterRolls5e and Health Monitor and Tabbed Chat

### ISSUE THREAD

**Issue by tyreal2004** [RedReign/FoundryVTT-BetterRolls5e#283]
Not sure why it's happening but the last update for some reason sent all my Health Monitor updates to OOC instead of showing up on the Rolls tab. Any ideas why this is happening? I have tried disabling other mods and it seems having BetterRolls5e on with Health Monitor seems to break it

**Comment by CarlosFdez** [comment]
I've been busy with pathfinder dev, but I can start looking into this soon.

**Comment by CarlosFdez** [comment]
I might need some more information. I don't see any problem from rolling a longsword with tabbed chatlog and health monitor enabled. Is there any combination of settings that triggers a problem? Maybe its been fixed in Foundry 0.8.7.

You did check the Rolls tab correct?
