### ISSUE TITLE
[FEATURE REQUEST] Add active effects icon to status list

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#287]
Hello,

When DAE is active, we can display a button to apply active effect to tokens. Which is amazing!!
But, it's kind of tedious to remove said effects, because we need to open up the sheet, click on the effect tab, and then click on the delete button. Especially when dealing with unliked tokens.

Would it be possible to add the active effect icon to the statuses list of the token as well? So we can toggle it there.
Not sure if it's a BetterRoll5e job, might be DAE (as well). Let me know, and I will open a request on the DAE repository.

![image](https://user-images.githubusercontent.com/1687854/122682167-2652fe80-d1f8-11eb-86e3-4a581440e415.png)

**Comment by CarlosFdez** [comment]
Suggest this to DAE. Its definitely not a better rolls thing, but being able to disable AE's from the token hud might be useful. I know PF2e allows that for their effects.

**Comment by DarKDinDoN** [comment]
Thx, it's done. Actually, I wrote to DAE & CUB. I think both (but not sure) could create the feature.

https://github.com/death-save/combat-utility-belt/issues/563
https://gitlab.com/tposney/dae/-/issues/178
