### ISSUE TITLE
Foundry 0.8.8 D&D 1.35 - Damage button no longer clickable, show prohibited symbol. 

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#288]
![image](https://user-images.githubusercontent.com/4083812/123446245-5d068b80-d5e1-11eb-8340-a15f70c9c8a7.png)

**Comment by cs96and** [comment]
I'm also getting the same on the "Apply Active Effects" button...
![image](https://user-images.githubusercontent.com/898086/123446791-2163c580-d5d1-11eb-8f6c-ddc2357c7c47.png)

**Comment by cs96and** [comment]
Possibly related bug in dnd5e system
https://gitlab.com/foundrynet/dnd5e/-/issues/1173

**Comment by kalibos** [comment]
Same issue. When BetterRolls is the only module enabled (including libWrapper, which is disabled), the button(s) are simply unclickable, as opposed to having the "prohibited" symbol.

**Comment by cs96and** [comment]
https://discord.com/channels/170995199584108546/848968683623022632/858034041421037598

> 🌈 unsoluble (he/him)
> Today at 18:20
> Core 5e has had erroneous disabled properties on things for ages, but we never noticed because up through 0.8.7 they were getting stripped by core Foundry HTML sanitization on chat cards. 0.8.8 relaxed this pass in various ways, letting them through for the first time. :upside_down_face: 

I tried removing the `disabled` attribute in the various html files in the templates directory and it fixes the issue.

**Comment by CarlosFdez** [comment]
the disabled prop predates my involvement and I thought it was necessary for something. Explains why the disabled prop was never picked up before. Easy fix, thanks for reporting.

**Comment by CarlosFdez** [comment]
And done, upgrade to 1.5.4 and let me know how it goes!

**Comment by apoapostolov** [comment]
Bug remains after updating to 1.3.6, may require change in Better Rolls?

**Comment by apoapostolov** [comment]
Fixed for me with 0.8.8 and 5E 1.3.6 and BR5E 1.5.4
