### ISSUE TITLE
Players getting Nan on damage rolls

### ISSUE THREAD

**Issue by dnf257** [RedReign/FoundryVTT-BetterRolls5e#290]
My players are getting Nan on damage rolls for both PC's and NPC's. The gamemaster however is not. I've tried uninstalling and reinstalling with no resolve. Deactivating the module fixes the NaN issue.

![mqxbiIE](https://user-images.githubusercontent.com/66557355/123682004-13e84e80-d810-11eb-9fc7-664a1c2cdbf3.png)
![p0RQq5z](https://user-images.githubusercontent.com/66557355/123682007-1480e500-d810-11eb-8910-8f84a027ca16.png)

**Comment by dnf257** [comment]
I should add this is on version 8.6 and 8.8 on foundry /dnd5e.

**Comment by CarlosFdez** [comment]
I am unable to reproduce this.  Are you running with only better rolls to see that its not a module interaction? I dragged in a young green dragon from the SRD and it doesn't look like that, so maybe you have an odd damage formula that causes problems in this scenario.

**Comment by MathewBissonnette** [comment]
Not the reporter, but also experiencing this. Looks like an issue when paired with Hide GM Rolls when the "Sanitize Better Rolls 5e Crit Damage" setting is enabled.

Disabling the Hide GM Rolls module or disabling that particular setting seems to fix the issue for me.

**Comment by Artetsu** [comment]
@MathewBissonnette I can confirm that Hide GM Rolls was indeed the culprit. Thank you for spotting this.

**Comment by dnf257** [comment]
Was for sure the Hide GM Rolls, thank you guys!
