### ISSUE TITLE
NAN on rolls

### ISSUE THREAD

**Issue by Artetsu** [RedReign/FoundryVTT-BetterRolls5e#291]
For some reason, players are getting NaN on rolls. I am not sure what I am supposed to do here.

For reference I am currently running 0.8.7.
![NaN rolls](https://user-images.githubusercontent.com/36137698/123721319-564c7280-d886-11eb-920c-7d7932dd7661.PNG)

**Comment by CarlosFdez** [comment]
I'm unable to reproduce it, as mentioned here:
https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/290

Will need a little more information. It may be due to a module interaction or a certain use case.

**Comment by Artetsu** [comment]
I have managed to resolve the issue by ticking off a box within the Hide GM rolls module settings. Thank you for your attention.
