### ISSUE TITLE
message.data.speaker.token in preCreateChatMessage is getting mangled to '[object Object]'

### ISSUE THREAD

**Issue by cs96and** [RedReign/FoundryVTT-BetterRolls5e#295]
Foundry: 0.8.8
Better Rolls: 1.5.5
Dnd5e: 1.3.6

When Better Rolls is enabled, `message.data.speaker.token` in `preCreateChatMessage()` is getting mangled to '[object Object]' when a roll is made from a sheet.

![image](https://user-images.githubusercontent.com/898086/125462945-5a9cd0e9-6c08-4791-a5b9-45f864ab22b3.png)

When Better Rolls is disabled, `token` is correctly set to the ID of the token that caused the roll.  I think the problem is on line 826 of custom-roll.js...

```javascript
		// Create the chat message
		const chatData = {
			user: game.user.id,
			content: await this.render(),
			speaker: {
				actor: actor?.id,
				token: actor?.token,  // <---- SHOULD HAVE  ?.id  on the end here
				alias: actor?.token?.name || actor?.name
			},
			flags: this._getFlags(),
			type: CONST.CHAT_MESSAGE_TYPES.ROLL,
			...Utils.getWhisperData(rollMode),

			// If not blank, D&D will try to modify the card...
			roll: new Roll("0").roll()
		};
```

**Comment by CarlosFdez** [comment]
You're 100% right. Shame I saw this only recently. Its an easy fix.

**Comment by cs96and** [comment]
I think it used to work fine in 0.7.x, but something changed in 0.8.x

**Comment by CarlosFdez** [comment]
In 0.8 I had to change some things but actor.token.id doesn't work either. For whatever reason actor.token is blank. However ChatMessage.getSpeaker() worked just fine. I just did the fix and it'll work on the next upate, I just need to work on your other MR first, and see if there's anything missing I should slip in as well.

**Comment by p4535992** [comment]
I think this issue is been solved no ?

**Comment by CarlosFdez** [comment]
Ah, yeah I believe so, I just didn't close the issue. I was more or less waiting for confirmation. Thanks for the heads up.
