### ISSUE TITLE
Feature request: ammunition with active effects & saving throws

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#298]
Hello,

Would it be possible to render the saving throw button and the active effect button for a ranged weapon when using an ammunition with a saving throw and or an active effect?

Right now, I'm kinda stuck:
- 1 crossbow
- poisoning ammunitions (saving throw + active effect)
- Paralyzing ammunitions (saving throw + active effect)

Scenarios:
- crossbow: attack & damages are OK. But I can't get either saving throws & active effects from the ammunitions
- poisoning & paralyzing ammunitions: damages, saving throws & active effect OK. But not the attack roll because the sheet doesn't allow for proficiency

**Comment by CarlosFdez** [comment]
I'll look into it, but I've been pretty busy so would appreciate a pull request if anyone is open to make one.

Saving throw not showing is a bug. Active Effect is a feature. Should probably do both though.

**Comment by DarKDinDoN** [comment]
@CarlosFdez took a shot at this: https://github.com/RedReign/FoundryVTT-BetterRolls5e/pull/299

**Comment by CarlosFdez** [comment]
Merged in. I need to do something for crash when I get time (making all actor skill rolls etc override the 5e methods) and then I'll do a release.
