### ISSUE TITLE
Cantrip scaling doesn't work

### ISSUE THREAD

**Issue by Azzurite** [RedReign/FoundryVTT-BetterRolls5e#3]
When you enable BetterRolls and roll a cantrip, its automatic level damage scaling does not work:

![grafik](https://user-images.githubusercontent.com/2777158/75811731-435a8880-5d8d-11ea-97dc-179f69309ef2.png)

This should say `2d6` (and it does, when BetterRolls is disabled), but with BetterRolls it say `NaNd6`.

Tested on Foundry 0.4.7

**Comment by RedReign** [comment]
Fixed! Thanks for the report!
