### ISSUE TITLE
Innate spellcasting doesn't consume charges

### ISSUE THREAD

**Issue by krysztalzg** [RedReign/FoundryVTT-BetterRolls5e#306]
As in title, I've enabled only tidy5e sheet and better rolls and issue persists, so it's Better Rolls thing. When casting spell marked as innate spellcasting the charge is not consumed.

**Comment by CarlosFdez** [comment]
So you need to enable "Uses" in the Better Rolls Tab when editing the spell. As of 1.6.4 spells should have Use enabled by default for any new spell, but for old ones you'll have to enable it manually.

**Comment by krysztalzg** [comment]
Great, shame on me for missing this checkbox in the config tab, thanks!
