### ISSUE TITLE
v0.6.0 of Foundry VTT compatibility

### ISSUE THREAD

**Issue by toadicusrex** [RedReign/FoundryVTT-BetterRolls5e#31]
I had just installed prior to the v0.6.0 upgrade for FoundryVTT.  If I enable the Better Rolls for 5e module, I get the following errors:

Uncaught SyntaxError: The requested module '../../../systems/dnd5e/module/pixi/ability-template.js' does not provide an export named 'default'
game:1 Uncaught SyntaxError: The requested module '../../../../systems/dnd5e/module/pixi/ability-template.js' does not provide an export named 'default'
2game:1 Uncaught SyntaxError: The requested module '../../../systems/dnd5e/module/pixi/ability-template.js' does not provide an export named 'default'

If I get time, and if I get my game set up for my Thursday game, I'll try to dig in a little and help figure out what's up.

**Comment by RedReign** [comment]
Hey - figured out the issue. It had to do with the path name - there was a typo. It should be fixed now!
