### ISSUE TITLE
Cannot delete chat message after reroll

### ISSUE THREAD

**Issue by Stewart12** [RedReign/FoundryVTT-BetterRolls5e#316]
**Description**
After rolling an attack and clicking advantage on that attack, any new chat messages created via the 'Repeat the Roll' button cannot  be removed.

**Steps to replicate**
1. Make a standard roll with any weapon
2. Click the + or - to give advantage or disadvantage
3. Click the 'Repeat the roll' button
* Note that the newly generated chat message cannot be deleted.

**Using**
FVTT: 0.8.9
DnD5e 1.4.2
Better Rolls 5e 1.6.8

![image](https://user-images.githubusercontent.com/38117828/131930389-163521b3-9f37-454b-8f2c-1d7812c960e9.png)

**Current Workaround**
Refreshing the page allows the delete option to reappear. Sometimes the previous attack chat message needs to be deleted to have this appear, but does not work without refreshing.

**Comment by CarlosFdez** [comment]
Anything error messages in the console (F12) when you do this?

**Comment by Stewart12** [comment]
No errors at all coming through the console.
Forgot to mention that I can replicate it across different browsers.

**Comment by CarlosFdez** [comment]
Couldn't reproduce locally on the latest 5e version at all. Maybe a module interaction of some sort.

**Comment by Stewart12** [comment]
You're right, I went through the arduous task of testing with all different modules and found that it's a module interaction between BRf5e and Plutonium.

**Comment by CarlosFdez** [comment]
If its what I think it is, I think there's a setting you can disable in that module that'll make it work.

**Comment by Stewart12** [comment]
You're right, disabling the 'Compact Chat' option within Plutonium setting resolved  the issue. Cheers for the help!
