### ISSUE TITLE
BetterRolls from the sheet ignore privacy settings for 3D Dice

### ISSUE THREAD

**Issue by JMMarchant** [RedReign/FoundryVTT-BetterRolls5e#32]
When setting roll mode to "Self Roll" and using both "Dice So Nice!" and BetterRolls5e, rolls from the sheet produce 3D dice that are visible to all players, rather than just to the player who rolled.

**Versions:** Foundry 0.6.0, dnd5e 0.91, Better Rolls for 5e 1.0.7, Dice So Nice! 1.7

Steps to reproduce:

1. Create a new world with the 5e system, Dice So Nice! and Better Rolls for 5e
2. Create a second player.
3. Login as both Gamemaster and the second player.
4. Enable 3D dice for both players.
5. Create a character sheet under the Gamemaster's control.
6. Set roll mode to "Self Roll" in the chat option.
7. Roll an ability check from the sheet as the Gamemaster; the second player will see the 3D dice roll but not the result in chat.

**Comment by JMMarchant** [comment]
This still seems to be happening in v1.0.8; is it supposed to be fixed in that version?

**Comment by RedReign** [comment]
Nope, the next update. Apologies for any confusion!
