### ISSUE TITLE
enhancement: prevent players from expanding card to see roll details

### ISSUE THREAD

**Issue by SR5060** [RedReign/FoundryVTT-BetterRolls5e#325]
would be great to have a setting to remove ability for players to expand the NPC card and see how the roll result was configured

**Comment by cs96and** [comment]
This is possible with the [Hide GM Rolls](https://foundryvtt.com/packages/hide-gm-rolls/) module

**Comment by CarlosFdez** [comment]
Thanks for the suggestion, but between Hide GM Rolls existing and core not allowing you to do that regardless, I likely won't be implementing it.

**Comment by SR5060** [comment]
Nope makes sense, I wasn't aware of hide gm rolls, so no use in duplicating features of that works with the module
