### ISSUE TITLE
Conflict between Dice So Nice and Better Rolls 5E when rolling NPC abilities

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#331]
DSN 4.2, BetterRolls5E 1.6.13
When both modules are loaded, roll chat messages are generated but do not show in the chat tab. On reload, they will appear but they do not immediately. Removing one of the mods fixes the behavior.

![image](https://user-images.githubusercontent.com/4083812/136665196-db0399ec-bf5e-4f7b-aeca-1a9f6e3bc13a.png)

**Comment by JiDW** [comment]
> 
> 
> In my world, this also seems to affect player characters too.

Update to the latest DsN version, it has been fixed

**Comment by CarlosFdez** [comment]
@JiDW thanks for this! Unfortunately this is a weirdness BR does because 5e hijacks the styling based on the roll result. And then later on because of delayed rolls when the damage button is turned on....
