### ISSUE TITLE
[BUG] 9.X When I open the "Stone Endurance" ability from a PC, I get "can't read quickOther" property"

### ISSUE THREAD

**Issue by marcottedan** [RedReign/FoundryVTT-BetterRolls5e#354]
If I open the Stone Endurance feature, I get a "can't read quickOther" property"

![image](https://user-images.githubusercontent.com/2078143/147594797-9608d6f9-1ef7-40ae-9bd2-7836cfd366e1.png)

**Comment by cs96and** [comment]
#365
