### ISSUE TITLE
stat bonus not added to attack or damage rolls

### ISSUE THREAD

**Issue by RulyTafzil** [RedReign/FoundryVTT-BetterRolls5e#36]
This seems too obvious so maybe I'm missing something, but when using this module the attack and damage rolls do not add the relevant attribute bonus to the roll.

**Comment by RedReign** [comment]
Do you have more details? Are you using a particular sheet? Any console errors?

**Comment by RulyTafzil** [comment]
I'm using the default sheet, dnd5e.ActorSheet5eCharacter
No errors in the console. 
When I switch between using betterrolls, mqol, and mess, the other roll systems seem to work? When I'm using better rolls, it just does straight rolls and doesn't add the attribute or prof bonus to the rolls. 

Looking at t he configuration settings for better rolls, I don't see anything that would cause this?

Anything else I can send you?

On v. 0.6.0 of VTT using 0.92 of the D&D55e module, 1.0.8 of Better Rolls.

**Comment by RedReign** [comment]
Can you show me a screenshot of the item's sheet, particularly the Details tab?

**Comment by RedReign** [comment]
Identified the issue, fixed in 1.1.0.
