### ISSUE TITLE
Conflict between Better Rolls DND 5e and Dynamic Effects

### ISSUE THREAD

**Issue by jputman** [RedReign/FoundryVTT-BetterRolls5e#38]
When Better Rolls DND 5e is in use, and you try to use an effect from the Dynamic Effects module it appears to be not taking into effect the change. My example is creating a Feat for Shield Master. Have it adding a passive bonus to dex saving throws. If I disable Better Rolls and do the roll, it adds the +2, where if I enable Better Rolls it ignores it. Even though it shows it on the actual sheet itself. 

![unknown (2)](https://user-images.githubusercontent.com/9375319/83218584-3656f680-a13c-11ea-845e-5faa2432902a.png)
![unknown (1)](https://user-images.githubusercontent.com/9375319/83218585-3656f680-a13c-11ea-8b05-7b96c478c034.png)
![unknown](https://user-images.githubusercontent.com/9375319/83218586-3656f680-a13c-11ea-9aca-ef2b0fa680f1.png)

**Comment by jputman** [comment]
So.. strangely enough, I believe that it is taking the bonus into account when using the automatic save from an attack, just not from manually rolling a saving through from the sheet.

**Comment by RedReign** [comment]
Unfortunately, there's no good way to incorporate a fix for this just yet. This is due to the way that bonuses are added/implemented.
