### ISSUE TITLE
Request: Allow for Single Rolls

### ISSUE THREAD

**Issue by yoman987** [RedReign/FoundryVTT-BetterRolls5e#4]
Hi RedReign, you're doing an amazing job :D 
I cant figure out how better to contact you than this, sorry.
Id like to request a setting to toggle single rolls rather than dual rolls. I've attempted to read thru the code and the css and change a thing here and there to no avail, I'm not experienced enough.

I'm thinking perhaps a default setting that decides which CSS template to use?
Whatever works, youre the boss :) Thank you
My email is sepomoyodee@gmail.com if youd prefer to email instead.

**Comment by apoapostolov** [comment]
I would like to second this, I would really use an option to turn off the dual rolls.

**Comment by RedReign** [comment]
Yep! My next big planned change for Better Rolls is to implement exactly this.
No ETA, but I imagine some point in the next few weeks will have that set properly as a feature, as well as some other improvements to go along with that change.
