### ISSUE TITLE
Blind GM rolls not working

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#40]
Hello,  

It seems that when a player is attempting to make a blind roll, the roll isn't hidden in the chat. It's send to the GM correctly, but the actual values are shown to the player instead of question marks.

**Comment by RedReign** [comment]
This is a known issue, as seen in the readme. Sadly I am unable to easily fix it due to the way that chat messages work with "OTHER"-type messages in Foundry. When Foundry updates the message functionality to let "OTHER"-type messages be blind, I will revisit this.
