### ISSUE TITLE
How to deal with sneak attack?

### ISSUE THREAD

**Issue by kpad-git** [RedReign/FoundryVTT-BetterRolls5e#44]
This might be a feature request, unless I am missing the answer. I can't see a great way to model the rogue's sneak attack. The ideal for me would be for the attack roll to be followed automatically by two damage rolls, one without sneak and one with sneak. That way I can apply the damage from the one that applies in a given attack round.

The closest I can come is to use the "other damage formula" to have the sneak dice get rolled for every weapon item the rogue has. That has 2 disadvantages - one is that I need to click in two places to apply the damage (one for sneak and one for regular), and two is that every item's formula needs updating every time the sneak dice level up.

If I make the "other formula" include the weapon's damage, it makes it one click for applying damage, but then there is a chance that the "with sneak roll" has much higher or lower damage since it has a different base damage roll (eg. 1d8+4+1d6 gets 1+4+4 = 9, while the original 1d8+4 gets 8+4=12).

Am I missing another way?

**Comment by RedReign** [comment]
You could simply add a feature called "Sneak Attack" that you click when you wish to apply sneak attack damage. 
Then, make the damage formula:
`(ceil(@classes.rogue.levels /2))d6`
An item that does exactly this already exists in the SRD compendium.
