### ISSUE TITLE
Melee weapon damages are using STR regardless of dropdown

### ISSUE THREAD

**Issue by JMMarchant** [RedReign/FoundryVTT-BetterRolls5e#46]
**Versions:** Foundry 0.6.0, dnd5e 0.92, BetterRolls 1.1.0

Regardless of what ability is chosen in the "Ability Modifier" dropdown for a melee weapon attack, Strength is used for the @mod part of the damage formula.

**Steps to reproduce:**
1. Create a new character, set STR to 6, DEX to 14.
2. Drag and drop a Quarterstaff from the SRD compendium to them.
3. Roll an attack by clicking the image: deals 1d6-2 damage as using STR.
4. Edit Quarterstaff to use "Dexterity" instead of "Default" in the "Ability Modifier" dropdown.
5. Roll an attack by clicking the image.

**Expected:** Attack rolls 1d6+2 damage due to DEX.

**Actual:** Attack still deals 1d6-2 damage as `@mod` is still using STR.

Disabling BetterRolls results in the desired behaviour for weapon damage.

**Comment by JMMarchant** [comment]
Digging into the debugger a bit, this looks like it occurs because [custom-rolls.js#L1086](https://github.com/RedReign/FoundryVTT-BetterRolls5e/blob/28385e53ebdcc1e4eec06aa08b561865b8f4f680/betterrolls5e/scripts/custom-roll.js#L1086) simply checks whether it's a melee weapon attack and sets the ability to strength.

I don't know where in here it would need to go but there probably needs to be a check whether the "Ability Modifier" dropdown is set to "Default" and if it is, do all the calculations for most efficient ability to use but otherwise just use what is set in the dropdown.

**Comment by DivertedCircle** [comment]
Can confirm this is happening with NPC's as well, not just characters.

**Comment by spookymonster** [comment]
Confirmed. Selecting Finesse tag does correct, but shouldn't be necessary.

**Comment by RedReign** [comment]
Thanks for the report, and thanks for the additional info, all three of you!
Should be a quick fix.

**Comment by RedReign** [comment]
Fixed in 1.1.1!
