### ISSUE TITLE
Private GM rolls are hidden instead of obsfucated

### ISSUE THREAD

**Issue by DeVelox** [RedReign/FoundryVTT-BetterRolls5e#47]
Versions: Foundry 0.6.1, dnd5e 0.92, BetterRolls 1.1.0

When using BetterRolls5e all rolls made as "private GM rolls" behave the same as "self" rolls in that they are completely hidden from chat rather than just having their results obsfucated.

When using default sheet rolls this is not the case and the distinction between GM rolls and self rolls is respected.

**Comment by RedReign** [comment]
Unfortunately, the nature of BRolls means it must use a different message type in Foundry code. This makes GM Rolls, Blind Rolls, and Self Rolls all behave somewhat differently, as those roll modes are only fully functional with "ROLL"-type messages, which is a type I cannot use.
See #40
