### ISSUE TITLE
Expose fullRollAttribute in betterrolls5e.js 

### ISSUE THREAD

**Issue by HyperGalak** [RedReign/FoundryVTT-BetterRolls5e#48]
Hello RedReign,
This module is great for dd5 users and dm. Excellent work!
I have just a little request : is it possible to expose CustomRolls.fullRollAttribute (like fullRollSkill) in BetterRolls ?
It would be easier for macro creators.
Also, is it possible to add an optional parameter to change the icon ?
Thanks
![image](https://user-images.githubusercontent.com/66535080/83955773-0ce24d00-a857-11ea-9cea-cc5377907349.png)

**Comment by RedReign** [comment]
Added the exposed function for for 1.1.2, thank you! Now there is a "rollCheck" and "rollSave", respectively. However , I don't have plans to change the icon for ability checks & saves at the moment.
