### ISSUE TITLE
ISSUE - NPC Skill checks do not follow chat output

### ISSUE THREAD

**Issue by Maelfros** [RedReign/FoundryVTT-BetterRolls5e#54]
If i change the chat option to private gm roll and click a NPC skill check from their respective skill sheet it will always output as a public roll.

**Comment by YuanRamirez** [comment]
This is also true for PCs and has to do with the fact that whisper IDs are never entered into the output of skill rolls.
fullRollSkill in custom-roll.js is missing 
`if (wd.whisper) { output.chatData.whisper = wd.whisper; }`
after line ~150

**Comment by RedReign** [comment]
Thanks, fixed in 1.1.5!
