### ISSUE TITLE
Versatile damage not working for spells

### ISSUE THREAD

**Issue by shawndibble** [RedReign/FoundryVTT-BetterRolls5e#55]
When doing versatile rolls for spells, the chat output will say versatile, but it will not use the versatile damage. Instead it uses the default regular damage. This can be seen when using Toll the Dead spell.

Issue appears to be from line 1198 of custom-roll.js. The code calls scaleDamage which doesn't take versatile rolls into consideration. Thus while the text output shows versatile, the roll itself is only from the formula.

Suggestion/Fix:
* Adjust ScaleDamage to accept forceVersatile so it uses the versatile value.
* Adjust scaling field to take a normal and a versatile option.

**Comment by RedReign** [comment]
Unsure if this'll be supported, as cantrip scaling for alternate "versatile" damage is only used in the Toll the Dead spell, to my knowledge.

I would normally recommend setting up your formulae as such:
![](https://i.imgur.com/ou8fZBH.png)
However, this many parentheses seems to break the roll formula parser. I imagine this will be resolved in the upcoming 0.7 update for Foundry.

**Comment by RedReign** [comment]
I've just had confirmed to me that you can use 
`(floor([@details.level + 7] / 6))d8`
`(floor([@details.level + 7] / 6))d12`
for your damage formulae. Make sure to also turn off Level Scaling.
