### ISSUE TITLE
Elven Accuracy is rolling 3 dies with disadvantage

### ISSUE THREAD

**Issue by Ikaguia** [RedReign/FoundryVTT-BetterRolls5e#56]
Elven accuracy is not meant to roll 3 dices when you have disadvantage.
I believe the issue is [here](https://github.com/RedReign/FoundryVTT-BetterRolls5e/blob/0dabbfee8a3511007da4072dae375ab98f69a2c7/betterrolls5e/scripts/custom-roll.js#L1010)

**Comment by RedReign** [comment]
Thanks, fixed for 1.1.5!
