### ISSUE TITLE
Feature Request: Toggleable Resource Consumption for Quick Rolls and Alt Quick Rolls

### ISSUE THREAD

**Issue by schultzcole** [RedReign/FoundryVTT-BetterRolls5e#57]
This is kind of a wishful thinking sort of request, but it'd be nice if you could configure in the "Better Rolls" tab of an item whether resources are consumed for quick rolls and alt quick rolls.

For example, if I have a sword which normally acts as a normal longsword, but the user can choose to expend a charge to add some extra damage each time they make an attack. It would be nice to be able to configure quick rolls like so:

- Standard Quick Roll: damage formula 0, resource consumption disabled
- Alt Quick Roll: damage formula 0, damage formula 1, resource consumption enabled.

**Comment by RedReign** [comment]
"Consume Charge" already does this, and should appear on items that either have Resource Consumption configured or have their own charges.
