### ISSUE TITLE
Attack Cards not Outputting Correctly to Chat.

### ISSUE THREAD

**Issue by Maelfros** [RedReign/FoundryVTT-BetterRolls5e#65]
The clean card that states attack and damage in a single message is only outputting as GM. 
![image](https://user-images.githubusercontent.com/25957143/85861599-9e761800-b78e-11ea-96e7-bbc15dbf9b30.png)
The first attack was output as the GM clicking on the rapier icon in the player inventory. Then clicking the same icon as a player outputs the attack and damage roll as two separate chat messages rather than the preferred one message.

**Comment by RedReign** [comment]
It seems like you have other mods that determine whether an attack hits or misses, which is also dependent on whether you are targeting a creature. Try disabling the other modules (I believe the one causing this issue is minor QOL, which has a setting to disable the "auto damage vs ac" feature.

**Comment by Maelfros** [comment]
Ok I will try that.

It’s just that it was working fine in previous versions for the auto apply damage and keeping the chat card outputs. Also as a gm it will still auto apply damage versus ac and output the better rolls chat card which seems odd to me. All my players are set at trusted permissions as well.

In the interim, I will disable that mqol feature.

Thanks


On Jun 26, 2020, at 12:13 PM, RedReign <notifications@github.com> wrote:

﻿

It seems like you have other mods that determine whether an attack hits or misses, which is also dependent on whether you are targeting a creature. Try disabling the other modules (I believe the one causing this issue is minor QOL, which has a setting to disable the "auto damage vs ac" feature.

**Comment by RedReign** [comment]
I can assure you, nothing has changed in my code that would have caused this issue. It's possible there's a configuration change (or maybe a mqol update) that caused this issue. I will investigate the issue more before closing.

**Comment by Maelfros** [comment]
Yea I wanted to let you know it was working before. It is very likely to be a conflict created through a mqol update. I can post an issue on that page as well.


On Jun 26, 2020, at 1:00 PM, RedReign <notifications@github.com> wrote:

﻿

I can assure you, nothing has changed in my code that would have caused this issue. It's possible there's a configuration change (or maybe a mqol update) that caused this issue. I will investigate the issue more before closing.

**Comment by tposney** [comment]
The option to use minor-qol speed item rolls is set per player (i.e. the split cards attack and damage). So if the dm is seeing the better rolls card and the players the split cards they should check their settings and disable minor-qol speed rolls.

**Comment by Maelfros** [comment]
Good to know. It was disabled for all the players already so must just be a minor qol issue

On Jun 27, 2020, at 9:28 AM, tposney <notifications@github.com> wrote:

﻿

The option to use minor-qol speed item rolls is set per player (i.e. the split cards attack and damage). So if the dm is seeing the better rolls card and the players the split cards they should check their settings and disable minor-qol speed rolls.
