### ISSUE TITLE
items are not being destroyed after use

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#67]
Hi,

Since last update, DnD 0.93 use a new system for item consumption. When the user clicks on an item, a confirm dialog is shown with the option to consume the item or not.

With that new system being rolled out, BetterRolls doesn't handle destruction of item upon consumption anymore.

**Comment by Javiondox** [comment]
Better Rolls for 5e version 1.1.7, Foundry 0.6.4, DnD5e 0.93.
Can confirm. The easier way to reproduce this bug is using any type of potion with charges.
Tested on Default and Tidy5e Sheets.

**Comment by RedReign** [comment]
Fixed in 1.1.9 - thanks!
