### ISSUE TITLE
Issue with Critical Damage on Better Rolls tab

### ISSUE THREAD

**Issue by tonyrobots** [RedReign/FoundryVTT-BetterRolls5e#68]
Apologies if I'm being dumb, but I'm trying to set the extra "vicious" damage on a weapon (2d6 on a natural 20) and the UI isn't cooperating. It doesn't match up with the screenshot you have in the readme, and I can't see how to get it to do what I want. Here's what I'm seeing:

![Annotation 2020-06-29 090809](https://user-images.githubusercontent.com/178870/86029489-155a1d80-b9e8-11ea-8ba1-03412e0fabb9.png)

**Comment by RulyTafzil** [comment]
Go back to the item details tab, and under the "Damage Formula" section, add a new formula, for 2d6 damage. Then you'll see it show up where you expect. 
![image](https://user-images.githubusercontent.com/16487374/86194160-a6bdb280-bb02-11ea-9a3a-5302d280491c.png)

**Comment by tonyrobots** [comment]
Ah, perfect. Thank you!

**Comment by RedReign** [comment]
This will be reworked at some point to let players input their own damage formulae for crits, rather than creating one formula and then choosing it from the dropdown.
