### ISSUE TITLE
Rolling crit during disadvantage still rolls crit dice

### ISSUE THREAD

**Issue by RulyTafzil** [RedReign/FoundryVTT-BetterRolls5e#69]
When a critical is rolled during a disadvantaged role, the damage roll still gives you critical damage dice. 

![image](https://user-images.githubusercontent.com/16487374/86194305-02883b80-bb03-11ea-9b06-65e84c6b2558.png)

Not really an issue I suppose since the ux asks if you want to apply crit dice or not, but it's a little confusing to explain to players.

**Comment by RedReign** [comment]
The functionality of Better Rolls often comes with the assumption that you use what you want to use, and don't use what you don't want to use, allowing you to give/take advantage/disadvantage after the roll's already been made (it's something that can happy somewhat often at my table, and others). At some point, I may make "unused" numbers more transparent, however.
