### ISSUE TITLE
Improvements for the Damage Chat Message

### ISSUE THREAD

**Issue by apoapostolov** [RedReign/FoundryVTT-BetterRolls5e#7]
When the chat message is expanded to look at individual rolls, write the damage type or label after each separate damage formula. If the formula has results for different types or labels, sum those with the same labels separately in separate total outputs that can be separately applied to target. 

For example the following formula

/r 1d6 slashing + 1 slashing + @prof slashing + @bonus slashing + @mod fire

would result in the following output, each pool would be marked either slashing or fire, and at the bottom of the chat message, there would be two bar fields for 10 slashing and 2 fire. 

![image](https://user-images.githubusercontent.com/4083812/79633552-dc433880-816e-11ea-9222-5e0ffb0915f3.png)

**Comment by RedReign** [comment]
Your damage rolls in the screenshot do not seem to be Better Rolls damage rolls. Not sure what you're asking for, as Better Rolls already supports separate total outputs...?
