### ISSUE TITLE
Minor Feature Request: Integration with Token Action HUD

### ISSUE THREAD

**Issue by p4535992** [RedReign/FoundryVTT-BetterRolls5e#71]
Some of my players love your module, but others love to use this [Token Action HUD](https://foundryvtt.com/packages/token-action-hud/).
It is possible to expand your module to intercept the rolls made with this other module?

**Comment by kimitsu** [comment]
Token Action HUD actually does have the setting to allow Better Rolls 5e to handle the rolls.

**Comment by espositos** [comment]
@p4535992 In the settings you can select Better Rolls 5e as your preferred roller. If there is a problem with it, feel free to report it to me and I can try to improve how it's implemented by the Token Action HUD, but there's nothing really to intercept on Better Roll's end

**Comment by p4535992** [comment]
Yea now i see the settings on the Token Action HUD configuration. 
Ty all for the patience.
