### ISSUE TITLE
Disabling 'Consume Charge' option doesn't prevent charges being consumed by 'Resource Consumption'

### ISSUE THREAD

**Issue by Ikaguia** [RedReign/FoundryVTT-BetterRolls5e#72]
If it makes a difference, it was a spell that uses 'ki points', and I tried doing alternative mode not use them (ritual casting).
![image](https://user-images.githubusercontent.com/16377028/86535707-a6ce0180-beb8-11ea-8a7a-aa56ef729fc9.png)
![image](https://user-images.githubusercontent.com/16377028/86535713-afbed300-beb8-11ea-8140-ca9af71f27bf.png)

**Comment by ColombianJulio** [comment]
This is an important issue to where I have removed better rolls. If I have an item that is considered a consumable and it has a charge, it will not recognize it and the charge gets use up and the item is at zero but the item stays in inventory.

**Comment by RedReign** [comment]
Fixed in the next update.
