### ISSUE TITLE
Felix's Chat Damage Buttons issue

### ISSUE THREAD

**Issue by Rinzlers** [RedReign/FoundryVTT-BetterRolls5e#75]
I updated to the latest beta 0.6.5 and the damage buttons to apply full/half healing or damage are not available.

**Comment by RedReign** [comment]
As far as I can tell, the chat damage buttons still work. Are there any red console logs (F12) when you load, or when you roll damage?

**Comment by Rinzlers** [comment]
I believe I was able to get the issue resolved.  I had another module that I thought I had disabled conflicting.  This can be closed.  Sorry for not being more thorough before posting.

**Comment by RedReign** [comment]
Thanks for reporting back!
