### ISSUE TITLE
Saving and Ability Throws fail to correctly roll

### ISSUE THREAD

**Issue by doggydude73** [RedReign/FoundryVTT-BetterRolls5e#76]
When updated with 1.1.8 Better Rolls and 0.65 Foundry, my players and I are getting errors trying to roll quick-rolls for Ability and Saving Throws.  The ability includes both straight stat rolls (like Str) and skills (like Acrobatics). 

![image](https://user-images.githubusercontent.com/4459418/86880245-19560180-c0b2-11ea-9477-f812c2d95401.png)

**Comment by MajorVictory** [comment]
I have a quick fix for this until an update can be made.
in scripts/custom-roll.js
change line 107 from:
`let dicePool = new Roll("").roll();`
to: 
`let dicePool = new Roll("0").roll();`

**Comment by RedReign** [comment]
Fixed in 1.1.9, thanks for the report!
