### ISSUE TITLE
Display Token Name in Chat Cards Instead of Actor Name

### ISSUE THREAD

**Issue by ZBell** [RedReign/FoundryVTT-BetterRolls5e#77]
Hello, I had a question and possibly a feature request.  I was wondering if it might be possible to display the Token's name in chat, rather than the Actor the token represents?  If this is not currently something BetterRolls can do, is it a feature that could be added in the future, or is it impossible?  Thank you for your time!

**Comment by RedReign** [comment]
Fixed as of 1.1.12!

**Comment by ZBell** [comment]
Awesome!  Great work on everything!
