### ISSUE TITLE
Feature Request: Don't auto roll damage

### ISSUE THREAD

**Issue by Brunhine** [RedReign/FoundryVTT-BetterRolls5e#8]
It would be nice to have an option to not roll damage unless clicked on, similar to the default rolls.

**Comment by RedReign** [comment]
I'm planning on implementing this with the next major 1.0 update!

**Comment by jennis0** [comment]
It would be great if there was an option to disable damage rolls only for spells with templates, as well as in general? I'm not a fan of my players seeing how much damage they'll do before they've decided who to attack!

**Comment by RedReign** [comment]
For that, I'd simply recommend you tell your players to configure the spell to roll damage on an Alt Roll, and place the template on a normal roll. Or simply tell your players to declare their target(s) before they actually roll the spell...

**Comment by RedReign** [comment]
Unfortunately I don't think your desired level of control in automation will be coming in the next update. I will, however, be making the "don't autoroll damage" a setting. And I may or may not include the ability to determine default Quick Roll settings for a new item in the next update as well, which will allow you to configure default settings for new items for each item type.

**Comment by CarlosFdez** [comment]
This is actually a feature I'm really interested in seeing. If you haven't started on it yet, I'd be tempted on giving it a shot. Was there a certain methodology you were thinking of? I know web dev but I've never worked on a Foundry module before.

**Comment by OuroDaiko** [comment]
Would love this, pretty much the only thing I don't care for about BetterRolls vs other like Midi-QOL. I would say that all this needs is a setting/way to place a button instead of auto-rolling damage.

**Comment by DrWiFi** [comment]
I would love this feature as well. I'm glad this is planned

**Comment by CarlosFdez** [comment]
Late reply but....implemented!
