### ISSUE TITLE
flags.dnd5e.weaponCriticalThreshold flag is only used on entities of type 'weapon'

### ISSUE THREAD

**Issue by MajorVictory** [RedReign/FoundryVTT-BetterRolls5e#83]
Referring to [custom-roll.js: Line 978](https://github.com/RedReign/FoundryVTT-BetterRolls5e/blob/92d49c5/betterrolls5e/scripts/custom-roll.js#L978)

With most item types being able to specify an action type it makes more sense to check the action type for the critical hit threshold.
I recommend replacing the line with:
`if (['mwak', 'rwak', 'msak', 'rsak'].includes(itemData.actionType)) {`

This would only apply the flag's critical hit threshold to a Melee Weapon/Spell Attack or a Ranged Weapon/Spell Attack and should not break existing functionality.

**Comment by RedReign** [comment]
At one point, i was under the impression that weapon critical threshold was specifically for weapon attacks. It's been made clear as dnd5e's developed that this was not truly the intent of this critical hit threshold in the actor's traits.

That said, I only want the critical threshold to apply to *weapon* attacks, not spell attacks. This is the intent of the Critical Threshold setting in the actor's Special Traits.

Thank you for the report though! The fix will be applied in the 1.1.11 update.
