### ISSUE TITLE
Unable to roll saves/checks with advantage from default Character Sheet

### ISSUE THREAD

**Issue by Voldemalort** [RedReign/FoundryVTT-BetterRolls5e#85]
When clicking on a stat name (e.g. Strength) from the character sheet, the behavior without BetterRolls5e is to prompt for a check or save, then to prompt for advantage/disadvantage. When BetterRolls5e is available, normally holding shift or ctrl will initiate an advantage/disadvantage roll on click, but since there is still a prompt for save/check the modifier is lost and never received by the better roll macro

**Comment by Voldemalort** [comment]
Being able to call a BetterRolls5e macro with an advantage/disadvantage parameter would also help greatly in macros

**Comment by RedReign** [comment]
You should be able to click the individual modifiers for checks and saves, holding Shift/Ctrl to apply Advantage/Disadvantage that way.
