### ISSUE TITLE
Roll Better not rolling crit damage in 0.7.0

### ISSUE THREAD

**Issue by DangrBoy** [RedReign/FoundryVTT-BetterRolls5e#87]
Subject pretty much covers it, Roll Better doesn't calculate/roll crit damage, nor does it highlight a nat 20 roll as green in 0.7.0. Even with all other modules disabled and all Better Roll options set to default.

Per the image the 20d under the 'Attack' tab is green, but the original '27' isn't and the crit die roll looks weird, rerolling a 1 once.

![Annotation 2020-08-02 145648](https://user-images.githubusercontent.com/69125101/89133429-90738f80-d4d0-11ea-9ecc-be03b6093030.png)

I get that Better Roll may not be compatible w. 0.7.0, but wanted to give you a heads up.

**Comment by figotech** [comment]
Can confirm: 0.7.2 alpha update the issue still persists, Even if crit damage is supposed to be max it doesnt show/add and the colors for 1s or 20's (or highest dice number) dont show up.  Hope it can be fixed soon
