### ISSUE TITLE
Compatibility with Item Macro

### ISSUE THREAD

**Issue by DarKDinDoN** [RedReign/FoundryVTT-BetterRolls5e#88]
Hello,

Item macro is an awesome module that lets us run macro from sheet directly: https://github.com/Kekilla0/Item-Macro

Is it possible to make BetterRolls compatible with this module?
If module is installed and activated and item macro is not empty, BetterRolls should execute the macro instead of the default action for an item.

Thx!

**Comment by shirkie** [comment]
I would love for these 2 modules to work together as well.  I encountered this error recently and it would make things much better if they were to work together!

**Comment by RedReign** [comment]
it is possible to accomplish this by unchecking the "Make Item Image Auto-roll" setting in Better Rolls' section in the Module Settings window.
https://i.imgur.com/ifWaQzo.png

**Comment by DarKDinDoN** [comment]
@RedReign You are suggesting to deactivate BetterRolls as the default click action for all items?
Is it possible to make BetterRolls detect if ItemMacro is activated on an item and execute ItemMacro instead?

**Comment by shirkie** [comment]
I agree with DarkDinDon.  I dont want to give up speed rolls if i dont have to.  It makes things so much easier.  Detecting if an item/feat/spell has an item macro tied to it and using that instead would be ideal.

**Comment by RedReign** [comment]
@DarKDinDoN Alright, I caved. Adding it into the next version of Better Rolls.

**Comment by shirkie** [comment]
Thank you so much for adding this in!  This adds so much functionality to my game!  Though i am on version 0.66.  It looks like i have to update to the0.7x series to get these changes, is that right?

**Comment by RedReign** [comment]
That is correct. Going forward, I am going to be supporting FVTT 0.7.x rather than 0.6.x

**Comment by shirkie** [comment]
Ok, that makes sense.  I'm trying to wait until the stable release before i update.  I was able to modify my old version based on your commit to get it working in the meantime until i update.  Thanks again!
