### ISSUE TITLE
Enabling "Make Item Image Auto-roll" allows spells to be cast when there are no spell slots.

### ISSUE THREAD

**Issue by sirrus233** [RedReign/FoundryVTT-BetterRolls5e#89]
Steps to reproduce:

1. Enable "Make Item Image Auto-roll"
2. Create a character actor with spells and slots
3. Set number of slots to 0
4. Attempt to cast the spell by clicking the image on the character sheet. Ignore the pop-up warning saying there are no available slots, and try to roll anyway. This will succeed, although it should fail.

**Comment by RedReign** [comment]
Fixed in 1.1.11. Thanks for the report!
