### ISSUE TITLE
Single rolls?

### ISSUE THREAD

**Issue by SirMoogle** [RedReign/FoundryVTT-BetterRolls5e#93]
Hi, I saw this issue being mentioned in #4. Has an option for it been implemented yet?

**Comment by Linith** [comment]
It's in the module settings for BetterRolls, there's a drop down. You can select between and dual rolls.

**Comment by SirMoogle** [comment]
Ah ok. I'm guessing it's a GM-only module setting?

**Comment by SirMoogle** [comment]
Well my GM tweaked the settings, so everything's good now. Thanks!
