### ISSUE TITLE
Editing Better Rolls Options Sends Me to Description Tab

### ISSUE THREAD

**Issue by Arquister** [RedReign/FoundryVTT-BetterRolls5e#94]
Whenever I try to edit one of the options within an item's "Better Rolls" tab, I am automatically sent to the item's "Description" tab as soon as I click on a setting.  This persists with all item types with a "Better Rolls" tab that I have tried, as well as on various character sheets (Default, Tidy 5e, DnD Beyond style, Default NPC).  Sort of a minor issue, just means a few extra clicks when editing those options, but thought you should be aware of it. 
![Better Rolls Video](https://user-images.githubusercontent.com/69589788/90026533-a9203a00-dc74-11ea-9934-700daf00821c.gif)

**Comment by RedReign** [comment]
Thanks for the report. I have known about this issue for a while and its solution has eluded me for some time. Hopefully, when I use the new Tabs API it will solve this annoying issue.

**Comment by RedReign** [comment]
Fixed in upcoming 1.1.12 (for Foundry 0.7.x)! Thanks again.
