### ISSUE TITLE
Rolls are not changed when using actors of the "vehicle" type

### ISSUE THREAD

**Issue by Hydrall** [RedReign/FoundryVTT-BetterRolls5e#98]
Seems to be pretty consistently the case; whether adding new weapons like a cannon or dragging and dropping in an otherwise functional SRD weapon, rolling the weapon from the vehicle's sheet provides a default roll rather than the module's.

**Comment by RedReign** [comment]
I've noticed some serious issues with vehicles at the moment (dnd5e 0.97), so I don't plan on supporting them just yet. Thanks for the report though!

**Comment by CarlosFdez** [comment]
And I believe we finally got around to it. If there's any more issues, feel free to make a new issue.
