### ISSUE TITLE
Query for advantage/disadvantage (Roll20-like)

### ISSUE THREAD

**Issue by krysztalzg** [RedReign/FoundryVTT-BetterRolls5e#99]
Hello, I'm transferring my games from Roll20 to Foundry and this module is improving the experience with rolls for my players, but we are missing ability to query Advantage/Disadvantage without use of keyboard. Just like on Roll20 when after clicking an ability there's prompt to choose roll type we would like to have new rolling mode beside single/dual. Do you think it's possible to implement?

**Comment by geoidesic** [comment]
But that's like the whole point of this module – to remove the dialog boxes. Why not just disable the module if that's what you want?

**Comment by krysztalzg** [comment]
Because this module also changes the roll results to look much better and vanilla dialog box i cluttered with modificators

**Comment by krysztalzg** [comment]
Well, I've forked and added the feature myself basing on the 1.1.9 version, so this can be closed.
